
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GovbrAuthRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GovbrAuthRequest
 * Estado de um login gov.br em andamento, entre o /authorize e o /callback.
 * 
 * Existe porque o fluxo OIDC é stateful e o projeto não tem sessão nem cookie:
 * o `state` prova que a resposta corresponde a um pedido nosso (anti-CSRF), o
 * `nonce` prova que o id_token é desta rodada (anti-replay) e o `codeVerifier`
 * é o segredo do PKCE, que NUNCA pode ir para o navegador.
 * 
 * `usedAt` garante uso único: sem isso, um `code` interceptado poderia ser
 * trocado de novo. `expiresAt` limita a janela de ataque e permite expurgo.
 * 
 * Só o app mobile usa gov.br; o admin continua com login por senha. Por isso
 * não há coluna de "cliente de origem" — o retorno sempre cai no mesmo lugar.
 */
export type GovbrAuthRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$GovbrAuthRequestPayload>

export type AggregateGovbrAuthRequest = {
  _count: GovbrAuthRequestCountAggregateOutputType | null
  _min: GovbrAuthRequestMinAggregateOutputType | null
  _max: GovbrAuthRequestMaxAggregateOutputType | null
}

export type GovbrAuthRequestMinAggregateOutputType = {
  state: string | null
  nonce: string | null
  codeVerifier: string | null
  redirectTo: string | null
  expiresAt: Date | null
  usedAt: Date | null
  createdAt: Date | null
}

export type GovbrAuthRequestMaxAggregateOutputType = {
  state: string | null
  nonce: string | null
  codeVerifier: string | null
  redirectTo: string | null
  expiresAt: Date | null
  usedAt: Date | null
  createdAt: Date | null
}

export type GovbrAuthRequestCountAggregateOutputType = {
  state: number
  nonce: number
  codeVerifier: number
  redirectTo: number
  expiresAt: number
  usedAt: number
  createdAt: number
  _all: number
}


export type GovbrAuthRequestMinAggregateInputType = {
  state?: true
  nonce?: true
  codeVerifier?: true
  redirectTo?: true
  expiresAt?: true
  usedAt?: true
  createdAt?: true
}

export type GovbrAuthRequestMaxAggregateInputType = {
  state?: true
  nonce?: true
  codeVerifier?: true
  redirectTo?: true
  expiresAt?: true
  usedAt?: true
  createdAt?: true
}

export type GovbrAuthRequestCountAggregateInputType = {
  state?: true
  nonce?: true
  codeVerifier?: true
  redirectTo?: true
  expiresAt?: true
  usedAt?: true
  createdAt?: true
  _all?: true
}

export type GovbrAuthRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GovbrAuthRequest to aggregate.
   */
  where?: Prisma.GovbrAuthRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GovbrAuthRequests to fetch.
   */
  orderBy?: Prisma.GovbrAuthRequestOrderByWithRelationInput | Prisma.GovbrAuthRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GovbrAuthRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GovbrAuthRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GovbrAuthRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GovbrAuthRequests
  **/
  _count?: true | GovbrAuthRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GovbrAuthRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GovbrAuthRequestMaxAggregateInputType
}

export type GetGovbrAuthRequestAggregateType<T extends GovbrAuthRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateGovbrAuthRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGovbrAuthRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateGovbrAuthRequest[P]>
}




export type GovbrAuthRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GovbrAuthRequestWhereInput
  orderBy?: Prisma.GovbrAuthRequestOrderByWithAggregationInput | Prisma.GovbrAuthRequestOrderByWithAggregationInput[]
  by: Prisma.GovbrAuthRequestScalarFieldEnum[] | Prisma.GovbrAuthRequestScalarFieldEnum
  having?: Prisma.GovbrAuthRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GovbrAuthRequestCountAggregateInputType | true
  _min?: GovbrAuthRequestMinAggregateInputType
  _max?: GovbrAuthRequestMaxAggregateInputType
}

export type GovbrAuthRequestGroupByOutputType = {
  state: string
  nonce: string
  codeVerifier: string
  redirectTo: string | null
  expiresAt: Date
  usedAt: Date | null
  createdAt: Date
  _count: GovbrAuthRequestCountAggregateOutputType | null
  _min: GovbrAuthRequestMinAggregateOutputType | null
  _max: GovbrAuthRequestMaxAggregateOutputType | null
}

export type GetGovbrAuthRequestGroupByPayload<T extends GovbrAuthRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GovbrAuthRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GovbrAuthRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GovbrAuthRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GovbrAuthRequestGroupByOutputType[P]>
      }
    >
  >



export type GovbrAuthRequestWhereInput = {
  AND?: Prisma.GovbrAuthRequestWhereInput | Prisma.GovbrAuthRequestWhereInput[]
  OR?: Prisma.GovbrAuthRequestWhereInput[]
  NOT?: Prisma.GovbrAuthRequestWhereInput | Prisma.GovbrAuthRequestWhereInput[]
  state?: Prisma.StringFilter<"GovbrAuthRequest"> | string
  nonce?: Prisma.StringFilter<"GovbrAuthRequest"> | string
  codeVerifier?: Prisma.StringFilter<"GovbrAuthRequest"> | string
  redirectTo?: Prisma.StringNullableFilter<"GovbrAuthRequest"> | string | null
  expiresAt?: Prisma.DateTimeFilter<"GovbrAuthRequest"> | Date | string
  usedAt?: Prisma.DateTimeNullableFilter<"GovbrAuthRequest"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"GovbrAuthRequest"> | Date | string
}

export type GovbrAuthRequestOrderByWithRelationInput = {
  state?: Prisma.SortOrder
  nonce?: Prisma.SortOrder
  codeVerifier?: Prisma.SortOrder
  redirectTo?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GovbrAuthRequestWhereUniqueInput = Prisma.AtLeast<{
  state?: string
  AND?: Prisma.GovbrAuthRequestWhereInput | Prisma.GovbrAuthRequestWhereInput[]
  OR?: Prisma.GovbrAuthRequestWhereInput[]
  NOT?: Prisma.GovbrAuthRequestWhereInput | Prisma.GovbrAuthRequestWhereInput[]
  nonce?: Prisma.StringFilter<"GovbrAuthRequest"> | string
  codeVerifier?: Prisma.StringFilter<"GovbrAuthRequest"> | string
  redirectTo?: Prisma.StringNullableFilter<"GovbrAuthRequest"> | string | null
  expiresAt?: Prisma.DateTimeFilter<"GovbrAuthRequest"> | Date | string
  usedAt?: Prisma.DateTimeNullableFilter<"GovbrAuthRequest"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"GovbrAuthRequest"> | Date | string
}, "state">

export type GovbrAuthRequestOrderByWithAggregationInput = {
  state?: Prisma.SortOrder
  nonce?: Prisma.SortOrder
  codeVerifier?: Prisma.SortOrder
  redirectTo?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.GovbrAuthRequestCountOrderByAggregateInput
  _max?: Prisma.GovbrAuthRequestMaxOrderByAggregateInput
  _min?: Prisma.GovbrAuthRequestMinOrderByAggregateInput
}

export type GovbrAuthRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.GovbrAuthRequestScalarWhereWithAggregatesInput | Prisma.GovbrAuthRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.GovbrAuthRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GovbrAuthRequestScalarWhereWithAggregatesInput | Prisma.GovbrAuthRequestScalarWhereWithAggregatesInput[]
  state?: Prisma.StringWithAggregatesFilter<"GovbrAuthRequest"> | string
  nonce?: Prisma.StringWithAggregatesFilter<"GovbrAuthRequest"> | string
  codeVerifier?: Prisma.StringWithAggregatesFilter<"GovbrAuthRequest"> | string
  redirectTo?: Prisma.StringNullableWithAggregatesFilter<"GovbrAuthRequest"> | string | null
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"GovbrAuthRequest"> | Date | string
  usedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"GovbrAuthRequest"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GovbrAuthRequest"> | Date | string
}

export type GovbrAuthRequestCreateInput = {
  state: string
  nonce: string
  codeVerifier: string
  redirectTo?: string | null
  expiresAt: Date | string
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type GovbrAuthRequestUncheckedCreateInput = {
  state: string
  nonce: string
  codeVerifier: string
  redirectTo?: string | null
  expiresAt: Date | string
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type GovbrAuthRequestUpdateInput = {
  state?: Prisma.StringFieldUpdateOperationsInput | string
  nonce?: Prisma.StringFieldUpdateOperationsInput | string
  codeVerifier?: Prisma.StringFieldUpdateOperationsInput | string
  redirectTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GovbrAuthRequestUncheckedUpdateInput = {
  state?: Prisma.StringFieldUpdateOperationsInput | string
  nonce?: Prisma.StringFieldUpdateOperationsInput | string
  codeVerifier?: Prisma.StringFieldUpdateOperationsInput | string
  redirectTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GovbrAuthRequestCreateManyInput = {
  state: string
  nonce: string
  codeVerifier: string
  redirectTo?: string | null
  expiresAt: Date | string
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type GovbrAuthRequestUpdateManyMutationInput = {
  state?: Prisma.StringFieldUpdateOperationsInput | string
  nonce?: Prisma.StringFieldUpdateOperationsInput | string
  codeVerifier?: Prisma.StringFieldUpdateOperationsInput | string
  redirectTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GovbrAuthRequestUncheckedUpdateManyInput = {
  state?: Prisma.StringFieldUpdateOperationsInput | string
  nonce?: Prisma.StringFieldUpdateOperationsInput | string
  codeVerifier?: Prisma.StringFieldUpdateOperationsInput | string
  redirectTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GovbrAuthRequestCountOrderByAggregateInput = {
  state?: Prisma.SortOrder
  nonce?: Prisma.SortOrder
  codeVerifier?: Prisma.SortOrder
  redirectTo?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GovbrAuthRequestMaxOrderByAggregateInput = {
  state?: Prisma.SortOrder
  nonce?: Prisma.SortOrder
  codeVerifier?: Prisma.SortOrder
  redirectTo?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GovbrAuthRequestMinOrderByAggregateInput = {
  state?: Prisma.SortOrder
  nonce?: Prisma.SortOrder
  codeVerifier?: Prisma.SortOrder
  redirectTo?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}



export type GovbrAuthRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  state?: boolean
  nonce?: boolean
  codeVerifier?: boolean
  redirectTo?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["govbrAuthRequest"]>

export type GovbrAuthRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  state?: boolean
  nonce?: boolean
  codeVerifier?: boolean
  redirectTo?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["govbrAuthRequest"]>

export type GovbrAuthRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  state?: boolean
  nonce?: boolean
  codeVerifier?: boolean
  redirectTo?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["govbrAuthRequest"]>

export type GovbrAuthRequestSelectScalar = {
  state?: boolean
  nonce?: boolean
  codeVerifier?: boolean
  redirectTo?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}

export type GovbrAuthRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"state" | "nonce" | "codeVerifier" | "redirectTo" | "expiresAt" | "usedAt" | "createdAt", ExtArgs["result"]["govbrAuthRequest"]>

export type $GovbrAuthRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GovbrAuthRequest"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    state: string
    nonce: string
    codeVerifier: string
    /**
     * Caminho relativo interno para onde levar o usuário depois do login.
     */
    redirectTo: string | null
    expiresAt: Date
    usedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["govbrAuthRequest"]>
  composites: {}
}

export type GovbrAuthRequestGetPayload<S extends boolean | null | undefined | GovbrAuthRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload, S>

export type GovbrAuthRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GovbrAuthRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GovbrAuthRequestCountAggregateInputType | true
  }

export interface GovbrAuthRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GovbrAuthRequest'], meta: { name: 'GovbrAuthRequest' } }
  /**
   * Find zero or one GovbrAuthRequest that matches the filter.
   * @param {GovbrAuthRequestFindUniqueArgs} args - Arguments to find a GovbrAuthRequest
   * @example
   * // Get one GovbrAuthRequest
   * const govbrAuthRequest = await prisma.govbrAuthRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GovbrAuthRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, GovbrAuthRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GovbrAuthRequestClient<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GovbrAuthRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GovbrAuthRequestFindUniqueOrThrowArgs} args - Arguments to find a GovbrAuthRequest
   * @example
   * // Get one GovbrAuthRequest
   * const govbrAuthRequest = await prisma.govbrAuthRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GovbrAuthRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GovbrAuthRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GovbrAuthRequestClient<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GovbrAuthRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrAuthRequestFindFirstArgs} args - Arguments to find a GovbrAuthRequest
   * @example
   * // Get one GovbrAuthRequest
   * const govbrAuthRequest = await prisma.govbrAuthRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GovbrAuthRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, GovbrAuthRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__GovbrAuthRequestClient<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GovbrAuthRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrAuthRequestFindFirstOrThrowArgs} args - Arguments to find a GovbrAuthRequest
   * @example
   * // Get one GovbrAuthRequest
   * const govbrAuthRequest = await prisma.govbrAuthRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GovbrAuthRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GovbrAuthRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GovbrAuthRequestClient<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GovbrAuthRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrAuthRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GovbrAuthRequests
   * const govbrAuthRequests = await prisma.govbrAuthRequest.findMany()
   * 
   * // Get first 10 GovbrAuthRequests
   * const govbrAuthRequests = await prisma.govbrAuthRequest.findMany({ take: 10 })
   * 
   * // Only select the `state`
   * const govbrAuthRequestWithStateOnly = await prisma.govbrAuthRequest.findMany({ select: { state: true } })
   * 
   */
  findMany<T extends GovbrAuthRequestFindManyArgs>(args?: Prisma.SelectSubset<T, GovbrAuthRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GovbrAuthRequest.
   * @param {GovbrAuthRequestCreateArgs} args - Arguments to create a GovbrAuthRequest.
   * @example
   * // Create one GovbrAuthRequest
   * const GovbrAuthRequest = await prisma.govbrAuthRequest.create({
   *   data: {
   *     // ... data to create a GovbrAuthRequest
   *   }
   * })
   * 
   */
  create<T extends GovbrAuthRequestCreateArgs>(args: Prisma.SelectSubset<T, GovbrAuthRequestCreateArgs<ExtArgs>>): Prisma.Prisma__GovbrAuthRequestClient<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GovbrAuthRequests.
   * @param {GovbrAuthRequestCreateManyArgs} args - Arguments to create many GovbrAuthRequests.
   * @example
   * // Create many GovbrAuthRequests
   * const govbrAuthRequest = await prisma.govbrAuthRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GovbrAuthRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, GovbrAuthRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GovbrAuthRequests and returns the data saved in the database.
   * @param {GovbrAuthRequestCreateManyAndReturnArgs} args - Arguments to create many GovbrAuthRequests.
   * @example
   * // Create many GovbrAuthRequests
   * const govbrAuthRequest = await prisma.govbrAuthRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GovbrAuthRequests and only return the `state`
   * const govbrAuthRequestWithStateOnly = await prisma.govbrAuthRequest.createManyAndReturn({
   *   select: { state: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GovbrAuthRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GovbrAuthRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GovbrAuthRequest.
   * @param {GovbrAuthRequestDeleteArgs} args - Arguments to delete one GovbrAuthRequest.
   * @example
   * // Delete one GovbrAuthRequest
   * const GovbrAuthRequest = await prisma.govbrAuthRequest.delete({
   *   where: {
   *     // ... filter to delete one GovbrAuthRequest
   *   }
   * })
   * 
   */
  delete<T extends GovbrAuthRequestDeleteArgs>(args: Prisma.SelectSubset<T, GovbrAuthRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__GovbrAuthRequestClient<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GovbrAuthRequest.
   * @param {GovbrAuthRequestUpdateArgs} args - Arguments to update one GovbrAuthRequest.
   * @example
   * // Update one GovbrAuthRequest
   * const govbrAuthRequest = await prisma.govbrAuthRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GovbrAuthRequestUpdateArgs>(args: Prisma.SelectSubset<T, GovbrAuthRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__GovbrAuthRequestClient<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GovbrAuthRequests.
   * @param {GovbrAuthRequestDeleteManyArgs} args - Arguments to filter GovbrAuthRequests to delete.
   * @example
   * // Delete a few GovbrAuthRequests
   * const { count } = await prisma.govbrAuthRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GovbrAuthRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, GovbrAuthRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GovbrAuthRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrAuthRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GovbrAuthRequests
   * const govbrAuthRequest = await prisma.govbrAuthRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GovbrAuthRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, GovbrAuthRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GovbrAuthRequests and returns the data updated in the database.
   * @param {GovbrAuthRequestUpdateManyAndReturnArgs} args - Arguments to update many GovbrAuthRequests.
   * @example
   * // Update many GovbrAuthRequests
   * const govbrAuthRequest = await prisma.govbrAuthRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GovbrAuthRequests and only return the `state`
   * const govbrAuthRequestWithStateOnly = await prisma.govbrAuthRequest.updateManyAndReturn({
   *   select: { state: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GovbrAuthRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GovbrAuthRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GovbrAuthRequest.
   * @param {GovbrAuthRequestUpsertArgs} args - Arguments to update or create a GovbrAuthRequest.
   * @example
   * // Update or create a GovbrAuthRequest
   * const govbrAuthRequest = await prisma.govbrAuthRequest.upsert({
   *   create: {
   *     // ... data to create a GovbrAuthRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GovbrAuthRequest we want to update
   *   }
   * })
   */
  upsert<T extends GovbrAuthRequestUpsertArgs>(args: Prisma.SelectSubset<T, GovbrAuthRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__GovbrAuthRequestClient<runtime.Types.Result.GetResult<Prisma.$GovbrAuthRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GovbrAuthRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrAuthRequestCountArgs} args - Arguments to filter GovbrAuthRequests to count.
   * @example
   * // Count the number of GovbrAuthRequests
   * const count = await prisma.govbrAuthRequest.count({
   *   where: {
   *     // ... the filter for the GovbrAuthRequests we want to count
   *   }
   * })
  **/
  count<T extends GovbrAuthRequestCountArgs>(
    args?: Prisma.Subset<T, GovbrAuthRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GovbrAuthRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GovbrAuthRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrAuthRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GovbrAuthRequestAggregateArgs>(args: Prisma.Subset<T, GovbrAuthRequestAggregateArgs>): Prisma.PrismaPromise<GetGovbrAuthRequestAggregateType<T>>

  /**
   * Group by GovbrAuthRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrAuthRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GovbrAuthRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GovbrAuthRequestGroupByArgs['orderBy'] }
      : { orderBy?: GovbrAuthRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GovbrAuthRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGovbrAuthRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GovbrAuthRequest model
 */
readonly fields: GovbrAuthRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GovbrAuthRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GovbrAuthRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GovbrAuthRequest model
 */
export interface GovbrAuthRequestFieldRefs {
  readonly state: Prisma.FieldRef<"GovbrAuthRequest", 'String'>
  readonly nonce: Prisma.FieldRef<"GovbrAuthRequest", 'String'>
  readonly codeVerifier: Prisma.FieldRef<"GovbrAuthRequest", 'String'>
  readonly redirectTo: Prisma.FieldRef<"GovbrAuthRequest", 'String'>
  readonly expiresAt: Prisma.FieldRef<"GovbrAuthRequest", 'DateTime'>
  readonly usedAt: Prisma.FieldRef<"GovbrAuthRequest", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"GovbrAuthRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GovbrAuthRequest findUnique
 */
export type GovbrAuthRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * Filter, which GovbrAuthRequest to fetch.
   */
  where: Prisma.GovbrAuthRequestWhereUniqueInput
}

/**
 * GovbrAuthRequest findUniqueOrThrow
 */
export type GovbrAuthRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * Filter, which GovbrAuthRequest to fetch.
   */
  where: Prisma.GovbrAuthRequestWhereUniqueInput
}

/**
 * GovbrAuthRequest findFirst
 */
export type GovbrAuthRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * Filter, which GovbrAuthRequest to fetch.
   */
  where?: Prisma.GovbrAuthRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GovbrAuthRequests to fetch.
   */
  orderBy?: Prisma.GovbrAuthRequestOrderByWithRelationInput | Prisma.GovbrAuthRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GovbrAuthRequests.
   */
  cursor?: Prisma.GovbrAuthRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GovbrAuthRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GovbrAuthRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GovbrAuthRequests.
   */
  distinct?: Prisma.GovbrAuthRequestScalarFieldEnum | Prisma.GovbrAuthRequestScalarFieldEnum[]
}

/**
 * GovbrAuthRequest findFirstOrThrow
 */
export type GovbrAuthRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * Filter, which GovbrAuthRequest to fetch.
   */
  where?: Prisma.GovbrAuthRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GovbrAuthRequests to fetch.
   */
  orderBy?: Prisma.GovbrAuthRequestOrderByWithRelationInput | Prisma.GovbrAuthRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GovbrAuthRequests.
   */
  cursor?: Prisma.GovbrAuthRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GovbrAuthRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GovbrAuthRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GovbrAuthRequests.
   */
  distinct?: Prisma.GovbrAuthRequestScalarFieldEnum | Prisma.GovbrAuthRequestScalarFieldEnum[]
}

/**
 * GovbrAuthRequest findMany
 */
export type GovbrAuthRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * Filter, which GovbrAuthRequests to fetch.
   */
  where?: Prisma.GovbrAuthRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GovbrAuthRequests to fetch.
   */
  orderBy?: Prisma.GovbrAuthRequestOrderByWithRelationInput | Prisma.GovbrAuthRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GovbrAuthRequests.
   */
  cursor?: Prisma.GovbrAuthRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GovbrAuthRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GovbrAuthRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GovbrAuthRequests.
   */
  distinct?: Prisma.GovbrAuthRequestScalarFieldEnum | Prisma.GovbrAuthRequestScalarFieldEnum[]
}

/**
 * GovbrAuthRequest create
 */
export type GovbrAuthRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * The data needed to create a GovbrAuthRequest.
   */
  data: Prisma.XOR<Prisma.GovbrAuthRequestCreateInput, Prisma.GovbrAuthRequestUncheckedCreateInput>
}

/**
 * GovbrAuthRequest createMany
 */
export type GovbrAuthRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GovbrAuthRequests.
   */
  data: Prisma.GovbrAuthRequestCreateManyInput | Prisma.GovbrAuthRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GovbrAuthRequest createManyAndReturn
 */
export type GovbrAuthRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * The data used to create many GovbrAuthRequests.
   */
  data: Prisma.GovbrAuthRequestCreateManyInput | Prisma.GovbrAuthRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GovbrAuthRequest update
 */
export type GovbrAuthRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * The data needed to update a GovbrAuthRequest.
   */
  data: Prisma.XOR<Prisma.GovbrAuthRequestUpdateInput, Prisma.GovbrAuthRequestUncheckedUpdateInput>
  /**
   * Choose, which GovbrAuthRequest to update.
   */
  where: Prisma.GovbrAuthRequestWhereUniqueInput
}

/**
 * GovbrAuthRequest updateMany
 */
export type GovbrAuthRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GovbrAuthRequests.
   */
  data: Prisma.XOR<Prisma.GovbrAuthRequestUpdateManyMutationInput, Prisma.GovbrAuthRequestUncheckedUpdateManyInput>
  /**
   * Filter which GovbrAuthRequests to update
   */
  where?: Prisma.GovbrAuthRequestWhereInput
  /**
   * Limit how many GovbrAuthRequests to update.
   */
  limit?: number
}

/**
 * GovbrAuthRequest updateManyAndReturn
 */
export type GovbrAuthRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * The data used to update GovbrAuthRequests.
   */
  data: Prisma.XOR<Prisma.GovbrAuthRequestUpdateManyMutationInput, Prisma.GovbrAuthRequestUncheckedUpdateManyInput>
  /**
   * Filter which GovbrAuthRequests to update
   */
  where?: Prisma.GovbrAuthRequestWhereInput
  /**
   * Limit how many GovbrAuthRequests to update.
   */
  limit?: number
}

/**
 * GovbrAuthRequest upsert
 */
export type GovbrAuthRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * The filter to search for the GovbrAuthRequest to update in case it exists.
   */
  where: Prisma.GovbrAuthRequestWhereUniqueInput
  /**
   * In case the GovbrAuthRequest found by the `where` argument doesn't exist, create a new GovbrAuthRequest with this data.
   */
  create: Prisma.XOR<Prisma.GovbrAuthRequestCreateInput, Prisma.GovbrAuthRequestUncheckedCreateInput>
  /**
   * In case the GovbrAuthRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GovbrAuthRequestUpdateInput, Prisma.GovbrAuthRequestUncheckedUpdateInput>
}

/**
 * GovbrAuthRequest delete
 */
export type GovbrAuthRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
  /**
   * Filter which GovbrAuthRequest to delete.
   */
  where: Prisma.GovbrAuthRequestWhereUniqueInput
}

/**
 * GovbrAuthRequest deleteMany
 */
export type GovbrAuthRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GovbrAuthRequests to delete
   */
  where?: Prisma.GovbrAuthRequestWhereInput
  /**
   * Limit how many GovbrAuthRequests to delete.
   */
  limit?: number
}

/**
 * GovbrAuthRequest without action
 */
export type GovbrAuthRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrAuthRequest
   */
  select?: Prisma.GovbrAuthRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrAuthRequest
   */
  omit?: Prisma.GovbrAuthRequestOmit<ExtArgs> | null
}
