
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GovbrPendingIdentity` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GovbrPendingIdentity
 * Identidade já validada no gov.br, aguardando um segundo passo do usuário:
 * provar posse da conta local existente, ou informar os dados que o gov.br
 * não fornece (data de nascimento e telefone).
 * 
 * Existe porque o `code` do gov.br é de uso único e já foi consumido quando
 * descobrimos que falta esse passo. Sem este comprovante de curta duração, a
 * segunda chamada não teria como provar que a pessoa autenticou de verdade —
 * e aceitar um CPF cru vindo do cliente seria o mesmo que não ter login.
 * 
 * Guardado no servidor, e não num token entregue ao navegador, para não
 * espalhar dado pessoal e para permitir invalidação por uso único.
 */
export type GovbrPendingIdentityModel = runtime.Types.Result.DefaultSelection<Prisma.$GovbrPendingIdentityPayload>

export type AggregateGovbrPendingIdentity = {
  _count: GovbrPendingIdentityCountAggregateOutputType | null
  _min: GovbrPendingIdentityMinAggregateOutputType | null
  _max: GovbrPendingIdentityMaxAggregateOutputType | null
}

export type GovbrPendingIdentityMinAggregateOutputType = {
  id: string | null
  govbrSub: string | null
  cpf: string | null
  name: string | null
  email: string | null
  picture: string | null
  redirectTo: string | null
  expiresAt: Date | null
  usedAt: Date | null
  createdAt: Date | null
}

export type GovbrPendingIdentityMaxAggregateOutputType = {
  id: string | null
  govbrSub: string | null
  cpf: string | null
  name: string | null
  email: string | null
  picture: string | null
  redirectTo: string | null
  expiresAt: Date | null
  usedAt: Date | null
  createdAt: Date | null
}

export type GovbrPendingIdentityCountAggregateOutputType = {
  id: number
  govbrSub: number
  cpf: number
  name: number
  email: number
  picture: number
  redirectTo: number
  expiresAt: number
  usedAt: number
  createdAt: number
  _all: number
}


export type GovbrPendingIdentityMinAggregateInputType = {
  id?: true
  govbrSub?: true
  cpf?: true
  name?: true
  email?: true
  picture?: true
  redirectTo?: true
  expiresAt?: true
  usedAt?: true
  createdAt?: true
}

export type GovbrPendingIdentityMaxAggregateInputType = {
  id?: true
  govbrSub?: true
  cpf?: true
  name?: true
  email?: true
  picture?: true
  redirectTo?: true
  expiresAt?: true
  usedAt?: true
  createdAt?: true
}

export type GovbrPendingIdentityCountAggregateInputType = {
  id?: true
  govbrSub?: true
  cpf?: true
  name?: true
  email?: true
  picture?: true
  redirectTo?: true
  expiresAt?: true
  usedAt?: true
  createdAt?: true
  _all?: true
}

export type GovbrPendingIdentityAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GovbrPendingIdentity to aggregate.
   */
  where?: Prisma.GovbrPendingIdentityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GovbrPendingIdentities to fetch.
   */
  orderBy?: Prisma.GovbrPendingIdentityOrderByWithRelationInput | Prisma.GovbrPendingIdentityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GovbrPendingIdentityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GovbrPendingIdentities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GovbrPendingIdentities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GovbrPendingIdentities
  **/
  _count?: true | GovbrPendingIdentityCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GovbrPendingIdentityMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GovbrPendingIdentityMaxAggregateInputType
}

export type GetGovbrPendingIdentityAggregateType<T extends GovbrPendingIdentityAggregateArgs> = {
      [P in keyof T & keyof AggregateGovbrPendingIdentity]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGovbrPendingIdentity[P]>
    : Prisma.GetScalarType<T[P], AggregateGovbrPendingIdentity[P]>
}




export type GovbrPendingIdentityGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GovbrPendingIdentityWhereInput
  orderBy?: Prisma.GovbrPendingIdentityOrderByWithAggregationInput | Prisma.GovbrPendingIdentityOrderByWithAggregationInput[]
  by: Prisma.GovbrPendingIdentityScalarFieldEnum[] | Prisma.GovbrPendingIdentityScalarFieldEnum
  having?: Prisma.GovbrPendingIdentityScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GovbrPendingIdentityCountAggregateInputType | true
  _min?: GovbrPendingIdentityMinAggregateInputType
  _max?: GovbrPendingIdentityMaxAggregateInputType
}

export type GovbrPendingIdentityGroupByOutputType = {
  id: string
  govbrSub: string
  cpf: string
  name: string
  email: string | null
  picture: string | null
  redirectTo: string | null
  expiresAt: Date
  usedAt: Date | null
  createdAt: Date
  _count: GovbrPendingIdentityCountAggregateOutputType | null
  _min: GovbrPendingIdentityMinAggregateOutputType | null
  _max: GovbrPendingIdentityMaxAggregateOutputType | null
}

export type GetGovbrPendingIdentityGroupByPayload<T extends GovbrPendingIdentityGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GovbrPendingIdentityGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GovbrPendingIdentityGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GovbrPendingIdentityGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GovbrPendingIdentityGroupByOutputType[P]>
      }
    >
  >



export type GovbrPendingIdentityWhereInput = {
  AND?: Prisma.GovbrPendingIdentityWhereInput | Prisma.GovbrPendingIdentityWhereInput[]
  OR?: Prisma.GovbrPendingIdentityWhereInput[]
  NOT?: Prisma.GovbrPendingIdentityWhereInput | Prisma.GovbrPendingIdentityWhereInput[]
  id?: Prisma.StringFilter<"GovbrPendingIdentity"> | string
  govbrSub?: Prisma.StringFilter<"GovbrPendingIdentity"> | string
  cpf?: Prisma.StringFilter<"GovbrPendingIdentity"> | string
  name?: Prisma.StringFilter<"GovbrPendingIdentity"> | string
  email?: Prisma.StringNullableFilter<"GovbrPendingIdentity"> | string | null
  picture?: Prisma.StringNullableFilter<"GovbrPendingIdentity"> | string | null
  redirectTo?: Prisma.StringNullableFilter<"GovbrPendingIdentity"> | string | null
  expiresAt?: Prisma.DateTimeFilter<"GovbrPendingIdentity"> | Date | string
  usedAt?: Prisma.DateTimeNullableFilter<"GovbrPendingIdentity"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"GovbrPendingIdentity"> | Date | string
}

export type GovbrPendingIdentityOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  govbrSub?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  picture?: Prisma.SortOrderInput | Prisma.SortOrder
  redirectTo?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GovbrPendingIdentityWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.GovbrPendingIdentityWhereInput | Prisma.GovbrPendingIdentityWhereInput[]
  OR?: Prisma.GovbrPendingIdentityWhereInput[]
  NOT?: Prisma.GovbrPendingIdentityWhereInput | Prisma.GovbrPendingIdentityWhereInput[]
  govbrSub?: Prisma.StringFilter<"GovbrPendingIdentity"> | string
  cpf?: Prisma.StringFilter<"GovbrPendingIdentity"> | string
  name?: Prisma.StringFilter<"GovbrPendingIdentity"> | string
  email?: Prisma.StringNullableFilter<"GovbrPendingIdentity"> | string | null
  picture?: Prisma.StringNullableFilter<"GovbrPendingIdentity"> | string | null
  redirectTo?: Prisma.StringNullableFilter<"GovbrPendingIdentity"> | string | null
  expiresAt?: Prisma.DateTimeFilter<"GovbrPendingIdentity"> | Date | string
  usedAt?: Prisma.DateTimeNullableFilter<"GovbrPendingIdentity"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"GovbrPendingIdentity"> | Date | string
}, "id">

export type GovbrPendingIdentityOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  govbrSub?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  picture?: Prisma.SortOrderInput | Prisma.SortOrder
  redirectTo?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.GovbrPendingIdentityCountOrderByAggregateInput
  _max?: Prisma.GovbrPendingIdentityMaxOrderByAggregateInput
  _min?: Prisma.GovbrPendingIdentityMinOrderByAggregateInput
}

export type GovbrPendingIdentityScalarWhereWithAggregatesInput = {
  AND?: Prisma.GovbrPendingIdentityScalarWhereWithAggregatesInput | Prisma.GovbrPendingIdentityScalarWhereWithAggregatesInput[]
  OR?: Prisma.GovbrPendingIdentityScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GovbrPendingIdentityScalarWhereWithAggregatesInput | Prisma.GovbrPendingIdentityScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GovbrPendingIdentity"> | string
  govbrSub?: Prisma.StringWithAggregatesFilter<"GovbrPendingIdentity"> | string
  cpf?: Prisma.StringWithAggregatesFilter<"GovbrPendingIdentity"> | string
  name?: Prisma.StringWithAggregatesFilter<"GovbrPendingIdentity"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"GovbrPendingIdentity"> | string | null
  picture?: Prisma.StringNullableWithAggregatesFilter<"GovbrPendingIdentity"> | string | null
  redirectTo?: Prisma.StringNullableWithAggregatesFilter<"GovbrPendingIdentity"> | string | null
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"GovbrPendingIdentity"> | Date | string
  usedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"GovbrPendingIdentity"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GovbrPendingIdentity"> | Date | string
}

export type GovbrPendingIdentityCreateInput = {
  id: string
  govbrSub: string
  cpf: string
  name: string
  email?: string | null
  picture?: string | null
  redirectTo?: string | null
  expiresAt: Date | string
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type GovbrPendingIdentityUncheckedCreateInput = {
  id: string
  govbrSub: string
  cpf: string
  name: string
  email?: string | null
  picture?: string | null
  redirectTo?: string | null
  expiresAt: Date | string
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type GovbrPendingIdentityUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  govbrSub?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  picture?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GovbrPendingIdentityUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  govbrSub?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  picture?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GovbrPendingIdentityCreateManyInput = {
  id: string
  govbrSub: string
  cpf: string
  name: string
  email?: string | null
  picture?: string | null
  redirectTo?: string | null
  expiresAt: Date | string
  usedAt?: Date | string | null
  createdAt?: Date | string
}

export type GovbrPendingIdentityUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  govbrSub?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  picture?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GovbrPendingIdentityUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  govbrSub?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  picture?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GovbrPendingIdentityCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  govbrSub?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  picture?: Prisma.SortOrder
  redirectTo?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GovbrPendingIdentityMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  govbrSub?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  picture?: Prisma.SortOrder
  redirectTo?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GovbrPendingIdentityMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  govbrSub?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  picture?: Prisma.SortOrder
  redirectTo?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}



export type GovbrPendingIdentitySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  govbrSub?: boolean
  cpf?: boolean
  name?: boolean
  email?: boolean
  picture?: boolean
  redirectTo?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["govbrPendingIdentity"]>

export type GovbrPendingIdentitySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  govbrSub?: boolean
  cpf?: boolean
  name?: boolean
  email?: boolean
  picture?: boolean
  redirectTo?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["govbrPendingIdentity"]>

export type GovbrPendingIdentitySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  govbrSub?: boolean
  cpf?: boolean
  name?: boolean
  email?: boolean
  picture?: boolean
  redirectTo?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["govbrPendingIdentity"]>

export type GovbrPendingIdentitySelectScalar = {
  id?: boolean
  govbrSub?: boolean
  cpf?: boolean
  name?: boolean
  email?: boolean
  picture?: boolean
  redirectTo?: boolean
  expiresAt?: boolean
  usedAt?: boolean
  createdAt?: boolean
}

export type GovbrPendingIdentityOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "govbrSub" | "cpf" | "name" | "email" | "picture" | "redirectTo" | "expiresAt" | "usedAt" | "createdAt", ExtArgs["result"]["govbrPendingIdentity"]>

export type $GovbrPendingIdentityPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GovbrPendingIdentity"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    govbrSub: string
    cpf: string
    name: string
    email: string | null
    picture: string | null
    redirectTo: string | null
    expiresAt: Date
    usedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["govbrPendingIdentity"]>
  composites: {}
}

export type GovbrPendingIdentityGetPayload<S extends boolean | null | undefined | GovbrPendingIdentityDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload, S>

export type GovbrPendingIdentityCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GovbrPendingIdentityFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GovbrPendingIdentityCountAggregateInputType | true
  }

export interface GovbrPendingIdentityDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GovbrPendingIdentity'], meta: { name: 'GovbrPendingIdentity' } }
  /**
   * Find zero or one GovbrPendingIdentity that matches the filter.
   * @param {GovbrPendingIdentityFindUniqueArgs} args - Arguments to find a GovbrPendingIdentity
   * @example
   * // Get one GovbrPendingIdentity
   * const govbrPendingIdentity = await prisma.govbrPendingIdentity.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GovbrPendingIdentityFindUniqueArgs>(args: Prisma.SelectSubset<T, GovbrPendingIdentityFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GovbrPendingIdentityClient<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GovbrPendingIdentity that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GovbrPendingIdentityFindUniqueOrThrowArgs} args - Arguments to find a GovbrPendingIdentity
   * @example
   * // Get one GovbrPendingIdentity
   * const govbrPendingIdentity = await prisma.govbrPendingIdentity.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GovbrPendingIdentityFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GovbrPendingIdentityFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GovbrPendingIdentityClient<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GovbrPendingIdentity that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrPendingIdentityFindFirstArgs} args - Arguments to find a GovbrPendingIdentity
   * @example
   * // Get one GovbrPendingIdentity
   * const govbrPendingIdentity = await prisma.govbrPendingIdentity.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GovbrPendingIdentityFindFirstArgs>(args?: Prisma.SelectSubset<T, GovbrPendingIdentityFindFirstArgs<ExtArgs>>): Prisma.Prisma__GovbrPendingIdentityClient<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GovbrPendingIdentity that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrPendingIdentityFindFirstOrThrowArgs} args - Arguments to find a GovbrPendingIdentity
   * @example
   * // Get one GovbrPendingIdentity
   * const govbrPendingIdentity = await prisma.govbrPendingIdentity.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GovbrPendingIdentityFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GovbrPendingIdentityFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GovbrPendingIdentityClient<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GovbrPendingIdentities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrPendingIdentityFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GovbrPendingIdentities
   * const govbrPendingIdentities = await prisma.govbrPendingIdentity.findMany()
   * 
   * // Get first 10 GovbrPendingIdentities
   * const govbrPendingIdentities = await prisma.govbrPendingIdentity.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const govbrPendingIdentityWithIdOnly = await prisma.govbrPendingIdentity.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GovbrPendingIdentityFindManyArgs>(args?: Prisma.SelectSubset<T, GovbrPendingIdentityFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GovbrPendingIdentity.
   * @param {GovbrPendingIdentityCreateArgs} args - Arguments to create a GovbrPendingIdentity.
   * @example
   * // Create one GovbrPendingIdentity
   * const GovbrPendingIdentity = await prisma.govbrPendingIdentity.create({
   *   data: {
   *     // ... data to create a GovbrPendingIdentity
   *   }
   * })
   * 
   */
  create<T extends GovbrPendingIdentityCreateArgs>(args: Prisma.SelectSubset<T, GovbrPendingIdentityCreateArgs<ExtArgs>>): Prisma.Prisma__GovbrPendingIdentityClient<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GovbrPendingIdentities.
   * @param {GovbrPendingIdentityCreateManyArgs} args - Arguments to create many GovbrPendingIdentities.
   * @example
   * // Create many GovbrPendingIdentities
   * const govbrPendingIdentity = await prisma.govbrPendingIdentity.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GovbrPendingIdentityCreateManyArgs>(args?: Prisma.SelectSubset<T, GovbrPendingIdentityCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GovbrPendingIdentities and returns the data saved in the database.
   * @param {GovbrPendingIdentityCreateManyAndReturnArgs} args - Arguments to create many GovbrPendingIdentities.
   * @example
   * // Create many GovbrPendingIdentities
   * const govbrPendingIdentity = await prisma.govbrPendingIdentity.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GovbrPendingIdentities and only return the `id`
   * const govbrPendingIdentityWithIdOnly = await prisma.govbrPendingIdentity.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GovbrPendingIdentityCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GovbrPendingIdentityCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GovbrPendingIdentity.
   * @param {GovbrPendingIdentityDeleteArgs} args - Arguments to delete one GovbrPendingIdentity.
   * @example
   * // Delete one GovbrPendingIdentity
   * const GovbrPendingIdentity = await prisma.govbrPendingIdentity.delete({
   *   where: {
   *     // ... filter to delete one GovbrPendingIdentity
   *   }
   * })
   * 
   */
  delete<T extends GovbrPendingIdentityDeleteArgs>(args: Prisma.SelectSubset<T, GovbrPendingIdentityDeleteArgs<ExtArgs>>): Prisma.Prisma__GovbrPendingIdentityClient<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GovbrPendingIdentity.
   * @param {GovbrPendingIdentityUpdateArgs} args - Arguments to update one GovbrPendingIdentity.
   * @example
   * // Update one GovbrPendingIdentity
   * const govbrPendingIdentity = await prisma.govbrPendingIdentity.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GovbrPendingIdentityUpdateArgs>(args: Prisma.SelectSubset<T, GovbrPendingIdentityUpdateArgs<ExtArgs>>): Prisma.Prisma__GovbrPendingIdentityClient<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GovbrPendingIdentities.
   * @param {GovbrPendingIdentityDeleteManyArgs} args - Arguments to filter GovbrPendingIdentities to delete.
   * @example
   * // Delete a few GovbrPendingIdentities
   * const { count } = await prisma.govbrPendingIdentity.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GovbrPendingIdentityDeleteManyArgs>(args?: Prisma.SelectSubset<T, GovbrPendingIdentityDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GovbrPendingIdentities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrPendingIdentityUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GovbrPendingIdentities
   * const govbrPendingIdentity = await prisma.govbrPendingIdentity.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GovbrPendingIdentityUpdateManyArgs>(args: Prisma.SelectSubset<T, GovbrPendingIdentityUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GovbrPendingIdentities and returns the data updated in the database.
   * @param {GovbrPendingIdentityUpdateManyAndReturnArgs} args - Arguments to update many GovbrPendingIdentities.
   * @example
   * // Update many GovbrPendingIdentities
   * const govbrPendingIdentity = await prisma.govbrPendingIdentity.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GovbrPendingIdentities and only return the `id`
   * const govbrPendingIdentityWithIdOnly = await prisma.govbrPendingIdentity.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GovbrPendingIdentityUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GovbrPendingIdentityUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GovbrPendingIdentity.
   * @param {GovbrPendingIdentityUpsertArgs} args - Arguments to update or create a GovbrPendingIdentity.
   * @example
   * // Update or create a GovbrPendingIdentity
   * const govbrPendingIdentity = await prisma.govbrPendingIdentity.upsert({
   *   create: {
   *     // ... data to create a GovbrPendingIdentity
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GovbrPendingIdentity we want to update
   *   }
   * })
   */
  upsert<T extends GovbrPendingIdentityUpsertArgs>(args: Prisma.SelectSubset<T, GovbrPendingIdentityUpsertArgs<ExtArgs>>): Prisma.Prisma__GovbrPendingIdentityClient<runtime.Types.Result.GetResult<Prisma.$GovbrPendingIdentityPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GovbrPendingIdentities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrPendingIdentityCountArgs} args - Arguments to filter GovbrPendingIdentities to count.
   * @example
   * // Count the number of GovbrPendingIdentities
   * const count = await prisma.govbrPendingIdentity.count({
   *   where: {
   *     // ... the filter for the GovbrPendingIdentities we want to count
   *   }
   * })
  **/
  count<T extends GovbrPendingIdentityCountArgs>(
    args?: Prisma.Subset<T, GovbrPendingIdentityCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GovbrPendingIdentityCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GovbrPendingIdentity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrPendingIdentityAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GovbrPendingIdentityAggregateArgs>(args: Prisma.Subset<T, GovbrPendingIdentityAggregateArgs>): Prisma.PrismaPromise<GetGovbrPendingIdentityAggregateType<T>>

  /**
   * Group by GovbrPendingIdentity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GovbrPendingIdentityGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GovbrPendingIdentityGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GovbrPendingIdentityGroupByArgs['orderBy'] }
      : { orderBy?: GovbrPendingIdentityGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GovbrPendingIdentityGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGovbrPendingIdentityGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GovbrPendingIdentity model
 */
readonly fields: GovbrPendingIdentityFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GovbrPendingIdentity.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GovbrPendingIdentityClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GovbrPendingIdentity model
 */
export interface GovbrPendingIdentityFieldRefs {
  readonly id: Prisma.FieldRef<"GovbrPendingIdentity", 'String'>
  readonly govbrSub: Prisma.FieldRef<"GovbrPendingIdentity", 'String'>
  readonly cpf: Prisma.FieldRef<"GovbrPendingIdentity", 'String'>
  readonly name: Prisma.FieldRef<"GovbrPendingIdentity", 'String'>
  readonly email: Prisma.FieldRef<"GovbrPendingIdentity", 'String'>
  readonly picture: Prisma.FieldRef<"GovbrPendingIdentity", 'String'>
  readonly redirectTo: Prisma.FieldRef<"GovbrPendingIdentity", 'String'>
  readonly expiresAt: Prisma.FieldRef<"GovbrPendingIdentity", 'DateTime'>
  readonly usedAt: Prisma.FieldRef<"GovbrPendingIdentity", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"GovbrPendingIdentity", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GovbrPendingIdentity findUnique
 */
export type GovbrPendingIdentityFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * Filter, which GovbrPendingIdentity to fetch.
   */
  where: Prisma.GovbrPendingIdentityWhereUniqueInput
}

/**
 * GovbrPendingIdentity findUniqueOrThrow
 */
export type GovbrPendingIdentityFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * Filter, which GovbrPendingIdentity to fetch.
   */
  where: Prisma.GovbrPendingIdentityWhereUniqueInput
}

/**
 * GovbrPendingIdentity findFirst
 */
export type GovbrPendingIdentityFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * Filter, which GovbrPendingIdentity to fetch.
   */
  where?: Prisma.GovbrPendingIdentityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GovbrPendingIdentities to fetch.
   */
  orderBy?: Prisma.GovbrPendingIdentityOrderByWithRelationInput | Prisma.GovbrPendingIdentityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GovbrPendingIdentities.
   */
  cursor?: Prisma.GovbrPendingIdentityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GovbrPendingIdentities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GovbrPendingIdentities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GovbrPendingIdentities.
   */
  distinct?: Prisma.GovbrPendingIdentityScalarFieldEnum | Prisma.GovbrPendingIdentityScalarFieldEnum[]
}

/**
 * GovbrPendingIdentity findFirstOrThrow
 */
export type GovbrPendingIdentityFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * Filter, which GovbrPendingIdentity to fetch.
   */
  where?: Prisma.GovbrPendingIdentityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GovbrPendingIdentities to fetch.
   */
  orderBy?: Prisma.GovbrPendingIdentityOrderByWithRelationInput | Prisma.GovbrPendingIdentityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GovbrPendingIdentities.
   */
  cursor?: Prisma.GovbrPendingIdentityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GovbrPendingIdentities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GovbrPendingIdentities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GovbrPendingIdentities.
   */
  distinct?: Prisma.GovbrPendingIdentityScalarFieldEnum | Prisma.GovbrPendingIdentityScalarFieldEnum[]
}

/**
 * GovbrPendingIdentity findMany
 */
export type GovbrPendingIdentityFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * Filter, which GovbrPendingIdentities to fetch.
   */
  where?: Prisma.GovbrPendingIdentityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GovbrPendingIdentities to fetch.
   */
  orderBy?: Prisma.GovbrPendingIdentityOrderByWithRelationInput | Prisma.GovbrPendingIdentityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GovbrPendingIdentities.
   */
  cursor?: Prisma.GovbrPendingIdentityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GovbrPendingIdentities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GovbrPendingIdentities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GovbrPendingIdentities.
   */
  distinct?: Prisma.GovbrPendingIdentityScalarFieldEnum | Prisma.GovbrPendingIdentityScalarFieldEnum[]
}

/**
 * GovbrPendingIdentity create
 */
export type GovbrPendingIdentityCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * The data needed to create a GovbrPendingIdentity.
   */
  data: Prisma.XOR<Prisma.GovbrPendingIdentityCreateInput, Prisma.GovbrPendingIdentityUncheckedCreateInput>
}

/**
 * GovbrPendingIdentity createMany
 */
export type GovbrPendingIdentityCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GovbrPendingIdentities.
   */
  data: Prisma.GovbrPendingIdentityCreateManyInput | Prisma.GovbrPendingIdentityCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GovbrPendingIdentity createManyAndReturn
 */
export type GovbrPendingIdentityCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * The data used to create many GovbrPendingIdentities.
   */
  data: Prisma.GovbrPendingIdentityCreateManyInput | Prisma.GovbrPendingIdentityCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GovbrPendingIdentity update
 */
export type GovbrPendingIdentityUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * The data needed to update a GovbrPendingIdentity.
   */
  data: Prisma.XOR<Prisma.GovbrPendingIdentityUpdateInput, Prisma.GovbrPendingIdentityUncheckedUpdateInput>
  /**
   * Choose, which GovbrPendingIdentity to update.
   */
  where: Prisma.GovbrPendingIdentityWhereUniqueInput
}

/**
 * GovbrPendingIdentity updateMany
 */
export type GovbrPendingIdentityUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GovbrPendingIdentities.
   */
  data: Prisma.XOR<Prisma.GovbrPendingIdentityUpdateManyMutationInput, Prisma.GovbrPendingIdentityUncheckedUpdateManyInput>
  /**
   * Filter which GovbrPendingIdentities to update
   */
  where?: Prisma.GovbrPendingIdentityWhereInput
  /**
   * Limit how many GovbrPendingIdentities to update.
   */
  limit?: number
}

/**
 * GovbrPendingIdentity updateManyAndReturn
 */
export type GovbrPendingIdentityUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * The data used to update GovbrPendingIdentities.
   */
  data: Prisma.XOR<Prisma.GovbrPendingIdentityUpdateManyMutationInput, Prisma.GovbrPendingIdentityUncheckedUpdateManyInput>
  /**
   * Filter which GovbrPendingIdentities to update
   */
  where?: Prisma.GovbrPendingIdentityWhereInput
  /**
   * Limit how many GovbrPendingIdentities to update.
   */
  limit?: number
}

/**
 * GovbrPendingIdentity upsert
 */
export type GovbrPendingIdentityUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * The filter to search for the GovbrPendingIdentity to update in case it exists.
   */
  where: Prisma.GovbrPendingIdentityWhereUniqueInput
  /**
   * In case the GovbrPendingIdentity found by the `where` argument doesn't exist, create a new GovbrPendingIdentity with this data.
   */
  create: Prisma.XOR<Prisma.GovbrPendingIdentityCreateInput, Prisma.GovbrPendingIdentityUncheckedCreateInput>
  /**
   * In case the GovbrPendingIdentity was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GovbrPendingIdentityUpdateInput, Prisma.GovbrPendingIdentityUncheckedUpdateInput>
}

/**
 * GovbrPendingIdentity delete
 */
export type GovbrPendingIdentityDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
  /**
   * Filter which GovbrPendingIdentity to delete.
   */
  where: Prisma.GovbrPendingIdentityWhereUniqueInput
}

/**
 * GovbrPendingIdentity deleteMany
 */
export type GovbrPendingIdentityDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GovbrPendingIdentities to delete
   */
  where?: Prisma.GovbrPendingIdentityWhereInput
  /**
   * Limit how many GovbrPendingIdentities to delete.
   */
  limit?: number
}

/**
 * GovbrPendingIdentity without action
 */
export type GovbrPendingIdentityDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GovbrPendingIdentity
   */
  select?: Prisma.GovbrPendingIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the GovbrPendingIdentity
   */
  omit?: Prisma.GovbrPendingIdentityOmit<ExtArgs> | null
}
