
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PrintRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PrintRequest
 * 
 */
export type PrintRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$PrintRequestPayload>

export type AggregatePrintRequest = {
  _count: PrintRequestCountAggregateOutputType | null
  _min: PrintRequestMinAggregateOutputType | null
  _max: PrintRequestMaxAggregateOutputType | null
}

export type PrintRequestMinAggregateOutputType = {
  id: string | null
  userId: string | null
  printerId: string | null
  purpose: string | null
  stlFileId: string | null
  gcodeFileId: string | null
  filamentId: string | null
  status: string | null
  rejectionCancelReason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PrintRequestMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  printerId: string | null
  purpose: string | null
  stlFileId: string | null
  gcodeFileId: string | null
  filamentId: string | null
  status: string | null
  rejectionCancelReason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PrintRequestCountAggregateOutputType = {
  id: number
  userId: number
  printerId: number
  purpose: number
  stlFileId: number
  gcodeFileId: number
  filamentId: number
  status: number
  rejectionCancelReason: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PrintRequestMinAggregateInputType = {
  id?: true
  userId?: true
  printerId?: true
  purpose?: true
  stlFileId?: true
  gcodeFileId?: true
  filamentId?: true
  status?: true
  rejectionCancelReason?: true
  createdAt?: true
  updatedAt?: true
}

export type PrintRequestMaxAggregateInputType = {
  id?: true
  userId?: true
  printerId?: true
  purpose?: true
  stlFileId?: true
  gcodeFileId?: true
  filamentId?: true
  status?: true
  rejectionCancelReason?: true
  createdAt?: true
  updatedAt?: true
}

export type PrintRequestCountAggregateInputType = {
  id?: true
  userId?: true
  printerId?: true
  purpose?: true
  stlFileId?: true
  gcodeFileId?: true
  filamentId?: true
  status?: true
  rejectionCancelReason?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PrintRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PrintRequest to aggregate.
   */
  where?: Prisma.PrintRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrintRequests to fetch.
   */
  orderBy?: Prisma.PrintRequestOrderByWithRelationInput | Prisma.PrintRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PrintRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrintRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrintRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PrintRequests
  **/
  _count?: true | PrintRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PrintRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PrintRequestMaxAggregateInputType
}

export type GetPrintRequestAggregateType<T extends PrintRequestAggregateArgs> = {
      [P in keyof T & keyof AggregatePrintRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePrintRequest[P]>
    : Prisma.GetScalarType<T[P], AggregatePrintRequest[P]>
}




export type PrintRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PrintRequestWhereInput
  orderBy?: Prisma.PrintRequestOrderByWithAggregationInput | Prisma.PrintRequestOrderByWithAggregationInput[]
  by: Prisma.PrintRequestScalarFieldEnum[] | Prisma.PrintRequestScalarFieldEnum
  having?: Prisma.PrintRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PrintRequestCountAggregateInputType | true
  _min?: PrintRequestMinAggregateInputType
  _max?: PrintRequestMaxAggregateInputType
}

export type PrintRequestGroupByOutputType = {
  id: string
  userId: string
  printerId: string | null
  purpose: string
  stlFileId: string
  gcodeFileId: string
  filamentId: string
  status: string
  rejectionCancelReason: string | null
  createdAt: Date
  updatedAt: Date
  _count: PrintRequestCountAggregateOutputType | null
  _min: PrintRequestMinAggregateOutputType | null
  _max: PrintRequestMaxAggregateOutputType | null
}

export type GetPrintRequestGroupByPayload<T extends PrintRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PrintRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PrintRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PrintRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PrintRequestGroupByOutputType[P]>
      }
    >
  >



export type PrintRequestWhereInput = {
  AND?: Prisma.PrintRequestWhereInput | Prisma.PrintRequestWhereInput[]
  OR?: Prisma.PrintRequestWhereInput[]
  NOT?: Prisma.PrintRequestWhereInput | Prisma.PrintRequestWhereInput[]
  id?: Prisma.StringFilter<"PrintRequest"> | string
  userId?: Prisma.StringFilter<"PrintRequest"> | string
  printerId?: Prisma.StringNullableFilter<"PrintRequest"> | string | null
  purpose?: Prisma.StringFilter<"PrintRequest"> | string
  stlFileId?: Prisma.StringFilter<"PrintRequest"> | string
  gcodeFileId?: Prisma.StringFilter<"PrintRequest"> | string
  filamentId?: Prisma.StringFilter<"PrintRequest"> | string
  status?: Prisma.StringFilter<"PrintRequest"> | string
  rejectionCancelReason?: Prisma.StringNullableFilter<"PrintRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PrintRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PrintRequest"> | Date | string
  stlFile?: Prisma.XOR<Prisma.FileScalarRelationFilter, Prisma.FileWhereInput>
  gcodeFile?: Prisma.XOR<Prisma.FileScalarRelationFilter, Prisma.FileWhereInput>
}

export type PrintRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  printerId?: Prisma.SortOrderInput | Prisma.SortOrder
  purpose?: Prisma.SortOrder
  stlFileId?: Prisma.SortOrder
  gcodeFileId?: Prisma.SortOrder
  filamentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectionCancelReason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  stlFile?: Prisma.FileOrderByWithRelationInput
  gcodeFile?: Prisma.FileOrderByWithRelationInput
}

export type PrintRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  stlFileId?: string
  gcodeFileId?: string
  AND?: Prisma.PrintRequestWhereInput | Prisma.PrintRequestWhereInput[]
  OR?: Prisma.PrintRequestWhereInput[]
  NOT?: Prisma.PrintRequestWhereInput | Prisma.PrintRequestWhereInput[]
  userId?: Prisma.StringFilter<"PrintRequest"> | string
  printerId?: Prisma.StringNullableFilter<"PrintRequest"> | string | null
  purpose?: Prisma.StringFilter<"PrintRequest"> | string
  filamentId?: Prisma.StringFilter<"PrintRequest"> | string
  status?: Prisma.StringFilter<"PrintRequest"> | string
  rejectionCancelReason?: Prisma.StringNullableFilter<"PrintRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PrintRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PrintRequest"> | Date | string
  stlFile?: Prisma.XOR<Prisma.FileScalarRelationFilter, Prisma.FileWhereInput>
  gcodeFile?: Prisma.XOR<Prisma.FileScalarRelationFilter, Prisma.FileWhereInput>
}, "id" | "stlFileId" | "gcodeFileId">

export type PrintRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  printerId?: Prisma.SortOrderInput | Prisma.SortOrder
  purpose?: Prisma.SortOrder
  stlFileId?: Prisma.SortOrder
  gcodeFileId?: Prisma.SortOrder
  filamentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectionCancelReason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PrintRequestCountOrderByAggregateInput
  _max?: Prisma.PrintRequestMaxOrderByAggregateInput
  _min?: Prisma.PrintRequestMinOrderByAggregateInput
}

export type PrintRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.PrintRequestScalarWhereWithAggregatesInput | Prisma.PrintRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.PrintRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PrintRequestScalarWhereWithAggregatesInput | Prisma.PrintRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PrintRequest"> | string
  userId?: Prisma.StringWithAggregatesFilter<"PrintRequest"> | string
  printerId?: Prisma.StringNullableWithAggregatesFilter<"PrintRequest"> | string | null
  purpose?: Prisma.StringWithAggregatesFilter<"PrintRequest"> | string
  stlFileId?: Prisma.StringWithAggregatesFilter<"PrintRequest"> | string
  gcodeFileId?: Prisma.StringWithAggregatesFilter<"PrintRequest"> | string
  filamentId?: Prisma.StringWithAggregatesFilter<"PrintRequest"> | string
  status?: Prisma.StringWithAggregatesFilter<"PrintRequest"> | string
  rejectionCancelReason?: Prisma.StringNullableWithAggregatesFilter<"PrintRequest"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PrintRequest"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PrintRequest"> | Date | string
}

export type PrintRequestCreateInput = {
  id: string
  userId: string
  printerId?: string | null
  purpose: string
  filamentId: string
  status: string
  rejectionCancelReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  stlFile: Prisma.FileCreateNestedOneWithoutPrintRequestStlInput
  gcodeFile: Prisma.FileCreateNestedOneWithoutPrintRequestGcodeInput
}

export type PrintRequestUncheckedCreateInput = {
  id: string
  userId: string
  printerId?: string | null
  purpose: string
  stlFileId: string
  gcodeFileId: string
  filamentId: string
  status: string
  rejectionCancelReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrintRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  printerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  purpose?: Prisma.StringFieldUpdateOperationsInput | string
  filamentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectionCancelReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stlFile?: Prisma.FileUpdateOneRequiredWithoutPrintRequestStlNestedInput
  gcodeFile?: Prisma.FileUpdateOneRequiredWithoutPrintRequestGcodeNestedInput
}

export type PrintRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  printerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  purpose?: Prisma.StringFieldUpdateOperationsInput | string
  stlFileId?: Prisma.StringFieldUpdateOperationsInput | string
  gcodeFileId?: Prisma.StringFieldUpdateOperationsInput | string
  filamentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectionCancelReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrintRequestCreateManyInput = {
  id: string
  userId: string
  printerId?: string | null
  purpose: string
  stlFileId: string
  gcodeFileId: string
  filamentId: string
  status: string
  rejectionCancelReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrintRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  printerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  purpose?: Prisma.StringFieldUpdateOperationsInput | string
  filamentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectionCancelReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrintRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  printerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  purpose?: Prisma.StringFieldUpdateOperationsInput | string
  stlFileId?: Prisma.StringFieldUpdateOperationsInput | string
  gcodeFileId?: Prisma.StringFieldUpdateOperationsInput | string
  filamentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectionCancelReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrintRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  printerId?: Prisma.SortOrder
  purpose?: Prisma.SortOrder
  stlFileId?: Prisma.SortOrder
  gcodeFileId?: Prisma.SortOrder
  filamentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectionCancelReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrintRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  printerId?: Prisma.SortOrder
  purpose?: Prisma.SortOrder
  stlFileId?: Prisma.SortOrder
  gcodeFileId?: Prisma.SortOrder
  filamentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectionCancelReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrintRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  printerId?: Prisma.SortOrder
  purpose?: Prisma.SortOrder
  stlFileId?: Prisma.SortOrder
  gcodeFileId?: Prisma.SortOrder
  filamentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectionCancelReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrintRequestNullableScalarRelationFilter = {
  is?: Prisma.PrintRequestWhereInput | null
  isNot?: Prisma.PrintRequestWhereInput | null
}

export type PrintRequestCreateNestedOneWithoutStlFileInput = {
  create?: Prisma.XOR<Prisma.PrintRequestCreateWithoutStlFileInput, Prisma.PrintRequestUncheckedCreateWithoutStlFileInput>
  connectOrCreate?: Prisma.PrintRequestCreateOrConnectWithoutStlFileInput
  connect?: Prisma.PrintRequestWhereUniqueInput
}

export type PrintRequestCreateNestedOneWithoutGcodeFileInput = {
  create?: Prisma.XOR<Prisma.PrintRequestCreateWithoutGcodeFileInput, Prisma.PrintRequestUncheckedCreateWithoutGcodeFileInput>
  connectOrCreate?: Prisma.PrintRequestCreateOrConnectWithoutGcodeFileInput
  connect?: Prisma.PrintRequestWhereUniqueInput
}

export type PrintRequestUncheckedCreateNestedOneWithoutStlFileInput = {
  create?: Prisma.XOR<Prisma.PrintRequestCreateWithoutStlFileInput, Prisma.PrintRequestUncheckedCreateWithoutStlFileInput>
  connectOrCreate?: Prisma.PrintRequestCreateOrConnectWithoutStlFileInput
  connect?: Prisma.PrintRequestWhereUniqueInput
}

export type PrintRequestUncheckedCreateNestedOneWithoutGcodeFileInput = {
  create?: Prisma.XOR<Prisma.PrintRequestCreateWithoutGcodeFileInput, Prisma.PrintRequestUncheckedCreateWithoutGcodeFileInput>
  connectOrCreate?: Prisma.PrintRequestCreateOrConnectWithoutGcodeFileInput
  connect?: Prisma.PrintRequestWhereUniqueInput
}

export type PrintRequestUpdateOneWithoutStlFileNestedInput = {
  create?: Prisma.XOR<Prisma.PrintRequestCreateWithoutStlFileInput, Prisma.PrintRequestUncheckedCreateWithoutStlFileInput>
  connectOrCreate?: Prisma.PrintRequestCreateOrConnectWithoutStlFileInput
  upsert?: Prisma.PrintRequestUpsertWithoutStlFileInput
  disconnect?: Prisma.PrintRequestWhereInput | boolean
  delete?: Prisma.PrintRequestWhereInput | boolean
  connect?: Prisma.PrintRequestWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PrintRequestUpdateToOneWithWhereWithoutStlFileInput, Prisma.PrintRequestUpdateWithoutStlFileInput>, Prisma.PrintRequestUncheckedUpdateWithoutStlFileInput>
}

export type PrintRequestUpdateOneWithoutGcodeFileNestedInput = {
  create?: Prisma.XOR<Prisma.PrintRequestCreateWithoutGcodeFileInput, Prisma.PrintRequestUncheckedCreateWithoutGcodeFileInput>
  connectOrCreate?: Prisma.PrintRequestCreateOrConnectWithoutGcodeFileInput
  upsert?: Prisma.PrintRequestUpsertWithoutGcodeFileInput
  disconnect?: Prisma.PrintRequestWhereInput | boolean
  delete?: Prisma.PrintRequestWhereInput | boolean
  connect?: Prisma.PrintRequestWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PrintRequestUpdateToOneWithWhereWithoutGcodeFileInput, Prisma.PrintRequestUpdateWithoutGcodeFileInput>, Prisma.PrintRequestUncheckedUpdateWithoutGcodeFileInput>
}

export type PrintRequestUncheckedUpdateOneWithoutStlFileNestedInput = {
  create?: Prisma.XOR<Prisma.PrintRequestCreateWithoutStlFileInput, Prisma.PrintRequestUncheckedCreateWithoutStlFileInput>
  connectOrCreate?: Prisma.PrintRequestCreateOrConnectWithoutStlFileInput
  upsert?: Prisma.PrintRequestUpsertWithoutStlFileInput
  disconnect?: Prisma.PrintRequestWhereInput | boolean
  delete?: Prisma.PrintRequestWhereInput | boolean
  connect?: Prisma.PrintRequestWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PrintRequestUpdateToOneWithWhereWithoutStlFileInput, Prisma.PrintRequestUpdateWithoutStlFileInput>, Prisma.PrintRequestUncheckedUpdateWithoutStlFileInput>
}

export type PrintRequestUncheckedUpdateOneWithoutGcodeFileNestedInput = {
  create?: Prisma.XOR<Prisma.PrintRequestCreateWithoutGcodeFileInput, Prisma.PrintRequestUncheckedCreateWithoutGcodeFileInput>
  connectOrCreate?: Prisma.PrintRequestCreateOrConnectWithoutGcodeFileInput
  upsert?: Prisma.PrintRequestUpsertWithoutGcodeFileInput
  disconnect?: Prisma.PrintRequestWhereInput | boolean
  delete?: Prisma.PrintRequestWhereInput | boolean
  connect?: Prisma.PrintRequestWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PrintRequestUpdateToOneWithWhereWithoutGcodeFileInput, Prisma.PrintRequestUpdateWithoutGcodeFileInput>, Prisma.PrintRequestUncheckedUpdateWithoutGcodeFileInput>
}

export type PrintRequestCreateWithoutStlFileInput = {
  id: string
  userId: string
  printerId?: string | null
  purpose: string
  filamentId: string
  status: string
  rejectionCancelReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  gcodeFile: Prisma.FileCreateNestedOneWithoutPrintRequestGcodeInput
}

export type PrintRequestUncheckedCreateWithoutStlFileInput = {
  id: string
  userId: string
  printerId?: string | null
  purpose: string
  gcodeFileId: string
  filamentId: string
  status: string
  rejectionCancelReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrintRequestCreateOrConnectWithoutStlFileInput = {
  where: Prisma.PrintRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.PrintRequestCreateWithoutStlFileInput, Prisma.PrintRequestUncheckedCreateWithoutStlFileInput>
}

export type PrintRequestCreateWithoutGcodeFileInput = {
  id: string
  userId: string
  printerId?: string | null
  purpose: string
  filamentId: string
  status: string
  rejectionCancelReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  stlFile: Prisma.FileCreateNestedOneWithoutPrintRequestStlInput
}

export type PrintRequestUncheckedCreateWithoutGcodeFileInput = {
  id: string
  userId: string
  printerId?: string | null
  purpose: string
  stlFileId: string
  filamentId: string
  status: string
  rejectionCancelReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrintRequestCreateOrConnectWithoutGcodeFileInput = {
  where: Prisma.PrintRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.PrintRequestCreateWithoutGcodeFileInput, Prisma.PrintRequestUncheckedCreateWithoutGcodeFileInput>
}

export type PrintRequestUpsertWithoutStlFileInput = {
  update: Prisma.XOR<Prisma.PrintRequestUpdateWithoutStlFileInput, Prisma.PrintRequestUncheckedUpdateWithoutStlFileInput>
  create: Prisma.XOR<Prisma.PrintRequestCreateWithoutStlFileInput, Prisma.PrintRequestUncheckedCreateWithoutStlFileInput>
  where?: Prisma.PrintRequestWhereInput
}

export type PrintRequestUpdateToOneWithWhereWithoutStlFileInput = {
  where?: Prisma.PrintRequestWhereInput
  data: Prisma.XOR<Prisma.PrintRequestUpdateWithoutStlFileInput, Prisma.PrintRequestUncheckedUpdateWithoutStlFileInput>
}

export type PrintRequestUpdateWithoutStlFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  printerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  purpose?: Prisma.StringFieldUpdateOperationsInput | string
  filamentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectionCancelReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gcodeFile?: Prisma.FileUpdateOneRequiredWithoutPrintRequestGcodeNestedInput
}

export type PrintRequestUncheckedUpdateWithoutStlFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  printerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  purpose?: Prisma.StringFieldUpdateOperationsInput | string
  gcodeFileId?: Prisma.StringFieldUpdateOperationsInput | string
  filamentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectionCancelReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrintRequestUpsertWithoutGcodeFileInput = {
  update: Prisma.XOR<Prisma.PrintRequestUpdateWithoutGcodeFileInput, Prisma.PrintRequestUncheckedUpdateWithoutGcodeFileInput>
  create: Prisma.XOR<Prisma.PrintRequestCreateWithoutGcodeFileInput, Prisma.PrintRequestUncheckedCreateWithoutGcodeFileInput>
  where?: Prisma.PrintRequestWhereInput
}

export type PrintRequestUpdateToOneWithWhereWithoutGcodeFileInput = {
  where?: Prisma.PrintRequestWhereInput
  data: Prisma.XOR<Prisma.PrintRequestUpdateWithoutGcodeFileInput, Prisma.PrintRequestUncheckedUpdateWithoutGcodeFileInput>
}

export type PrintRequestUpdateWithoutGcodeFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  printerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  purpose?: Prisma.StringFieldUpdateOperationsInput | string
  filamentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectionCancelReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stlFile?: Prisma.FileUpdateOneRequiredWithoutPrintRequestStlNestedInput
}

export type PrintRequestUncheckedUpdateWithoutGcodeFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  printerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  purpose?: Prisma.StringFieldUpdateOperationsInput | string
  stlFileId?: Prisma.StringFieldUpdateOperationsInput | string
  filamentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectionCancelReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PrintRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  printerId?: boolean
  purpose?: boolean
  stlFileId?: boolean
  gcodeFileId?: boolean
  filamentId?: boolean
  status?: boolean
  rejectionCancelReason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  stlFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
  gcodeFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["printRequest"]>

export type PrintRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  printerId?: boolean
  purpose?: boolean
  stlFileId?: boolean
  gcodeFileId?: boolean
  filamentId?: boolean
  status?: boolean
  rejectionCancelReason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  stlFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
  gcodeFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["printRequest"]>

export type PrintRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  printerId?: boolean
  purpose?: boolean
  stlFileId?: boolean
  gcodeFileId?: boolean
  filamentId?: boolean
  status?: boolean
  rejectionCancelReason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  stlFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
  gcodeFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["printRequest"]>

export type PrintRequestSelectScalar = {
  id?: boolean
  userId?: boolean
  printerId?: boolean
  purpose?: boolean
  stlFileId?: boolean
  gcodeFileId?: boolean
  filamentId?: boolean
  status?: boolean
  rejectionCancelReason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PrintRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "printerId" | "purpose" | "stlFileId" | "gcodeFileId" | "filamentId" | "status" | "rejectionCancelReason" | "createdAt" | "updatedAt", ExtArgs["result"]["printRequest"]>
export type PrintRequestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  stlFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
  gcodeFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
}
export type PrintRequestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  stlFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
  gcodeFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
}
export type PrintRequestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  stlFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
  gcodeFile?: boolean | Prisma.FileDefaultArgs<ExtArgs>
}

export type $PrintRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PrintRequest"
  objects: {
    stlFile: Prisma.$FilePayload<ExtArgs>
    gcodeFile: Prisma.$FilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    printerId: string | null
    purpose: string
    stlFileId: string
    gcodeFileId: string
    filamentId: string
    status: string
    rejectionCancelReason: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["printRequest"]>
  composites: {}
}

export type PrintRequestGetPayload<S extends boolean | null | undefined | PrintRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload, S>

export type PrintRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PrintRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PrintRequestCountAggregateInputType | true
  }

export interface PrintRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PrintRequest'], meta: { name: 'PrintRequest' } }
  /**
   * Find zero or one PrintRequest that matches the filter.
   * @param {PrintRequestFindUniqueArgs} args - Arguments to find a PrintRequest
   * @example
   * // Get one PrintRequest
   * const printRequest = await prisma.printRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PrintRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, PrintRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PrintRequestClient<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PrintRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PrintRequestFindUniqueOrThrowArgs} args - Arguments to find a PrintRequest
   * @example
   * // Get one PrintRequest
   * const printRequest = await prisma.printRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PrintRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PrintRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrintRequestClient<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PrintRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrintRequestFindFirstArgs} args - Arguments to find a PrintRequest
   * @example
   * // Get one PrintRequest
   * const printRequest = await prisma.printRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PrintRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, PrintRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__PrintRequestClient<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PrintRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrintRequestFindFirstOrThrowArgs} args - Arguments to find a PrintRequest
   * @example
   * // Get one PrintRequest
   * const printRequest = await prisma.printRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PrintRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PrintRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrintRequestClient<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PrintRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrintRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PrintRequests
   * const printRequests = await prisma.printRequest.findMany()
   * 
   * // Get first 10 PrintRequests
   * const printRequests = await prisma.printRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const printRequestWithIdOnly = await prisma.printRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PrintRequestFindManyArgs>(args?: Prisma.SelectSubset<T, PrintRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PrintRequest.
   * @param {PrintRequestCreateArgs} args - Arguments to create a PrintRequest.
   * @example
   * // Create one PrintRequest
   * const PrintRequest = await prisma.printRequest.create({
   *   data: {
   *     // ... data to create a PrintRequest
   *   }
   * })
   * 
   */
  create<T extends PrintRequestCreateArgs>(args: Prisma.SelectSubset<T, PrintRequestCreateArgs<ExtArgs>>): Prisma.Prisma__PrintRequestClient<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PrintRequests.
   * @param {PrintRequestCreateManyArgs} args - Arguments to create many PrintRequests.
   * @example
   * // Create many PrintRequests
   * const printRequest = await prisma.printRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PrintRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, PrintRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PrintRequests and returns the data saved in the database.
   * @param {PrintRequestCreateManyAndReturnArgs} args - Arguments to create many PrintRequests.
   * @example
   * // Create many PrintRequests
   * const printRequest = await prisma.printRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PrintRequests and only return the `id`
   * const printRequestWithIdOnly = await prisma.printRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PrintRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PrintRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PrintRequest.
   * @param {PrintRequestDeleteArgs} args - Arguments to delete one PrintRequest.
   * @example
   * // Delete one PrintRequest
   * const PrintRequest = await prisma.printRequest.delete({
   *   where: {
   *     // ... filter to delete one PrintRequest
   *   }
   * })
   * 
   */
  delete<T extends PrintRequestDeleteArgs>(args: Prisma.SelectSubset<T, PrintRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__PrintRequestClient<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PrintRequest.
   * @param {PrintRequestUpdateArgs} args - Arguments to update one PrintRequest.
   * @example
   * // Update one PrintRequest
   * const printRequest = await prisma.printRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PrintRequestUpdateArgs>(args: Prisma.SelectSubset<T, PrintRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__PrintRequestClient<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PrintRequests.
   * @param {PrintRequestDeleteManyArgs} args - Arguments to filter PrintRequests to delete.
   * @example
   * // Delete a few PrintRequests
   * const { count } = await prisma.printRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PrintRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, PrintRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PrintRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrintRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PrintRequests
   * const printRequest = await prisma.printRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PrintRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, PrintRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PrintRequests and returns the data updated in the database.
   * @param {PrintRequestUpdateManyAndReturnArgs} args - Arguments to update many PrintRequests.
   * @example
   * // Update many PrintRequests
   * const printRequest = await prisma.printRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PrintRequests and only return the `id`
   * const printRequestWithIdOnly = await prisma.printRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PrintRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PrintRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PrintRequest.
   * @param {PrintRequestUpsertArgs} args - Arguments to update or create a PrintRequest.
   * @example
   * // Update or create a PrintRequest
   * const printRequest = await prisma.printRequest.upsert({
   *   create: {
   *     // ... data to create a PrintRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PrintRequest we want to update
   *   }
   * })
   */
  upsert<T extends PrintRequestUpsertArgs>(args: Prisma.SelectSubset<T, PrintRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__PrintRequestClient<runtime.Types.Result.GetResult<Prisma.$PrintRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PrintRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrintRequestCountArgs} args - Arguments to filter PrintRequests to count.
   * @example
   * // Count the number of PrintRequests
   * const count = await prisma.printRequest.count({
   *   where: {
   *     // ... the filter for the PrintRequests we want to count
   *   }
   * })
  **/
  count<T extends PrintRequestCountArgs>(
    args?: Prisma.Subset<T, PrintRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PrintRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PrintRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrintRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PrintRequestAggregateArgs>(args: Prisma.Subset<T, PrintRequestAggregateArgs>): Prisma.PrismaPromise<GetPrintRequestAggregateType<T>>

  /**
   * Group by PrintRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrintRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PrintRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PrintRequestGroupByArgs['orderBy'] }
      : { orderBy?: PrintRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PrintRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPrintRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PrintRequest model
 */
readonly fields: PrintRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PrintRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PrintRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  stlFile<T extends Prisma.FileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FileDefaultArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  gcodeFile<T extends Prisma.FileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FileDefaultArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PrintRequest model
 */
export interface PrintRequestFieldRefs {
  readonly id: Prisma.FieldRef<"PrintRequest", 'String'>
  readonly userId: Prisma.FieldRef<"PrintRequest", 'String'>
  readonly printerId: Prisma.FieldRef<"PrintRequest", 'String'>
  readonly purpose: Prisma.FieldRef<"PrintRequest", 'String'>
  readonly stlFileId: Prisma.FieldRef<"PrintRequest", 'String'>
  readonly gcodeFileId: Prisma.FieldRef<"PrintRequest", 'String'>
  readonly filamentId: Prisma.FieldRef<"PrintRequest", 'String'>
  readonly status: Prisma.FieldRef<"PrintRequest", 'String'>
  readonly rejectionCancelReason: Prisma.FieldRef<"PrintRequest", 'String'>
  readonly createdAt: Prisma.FieldRef<"PrintRequest", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PrintRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PrintRequest findUnique
 */
export type PrintRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestInclude<ExtArgs> | null
  /**
   * Filter, which PrintRequest to fetch.
   */
  where: Prisma.PrintRequestWhereUniqueInput
}

/**
 * PrintRequest findUniqueOrThrow
 */
export type PrintRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestInclude<ExtArgs> | null
  /**
   * Filter, which PrintRequest to fetch.
   */
  where: Prisma.PrintRequestWhereUniqueInput
}

/**
 * PrintRequest findFirst
 */
export type PrintRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestInclude<ExtArgs> | null
  /**
   * Filter, which PrintRequest to fetch.
   */
  where?: Prisma.PrintRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrintRequests to fetch.
   */
  orderBy?: Prisma.PrintRequestOrderByWithRelationInput | Prisma.PrintRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PrintRequests.
   */
  cursor?: Prisma.PrintRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrintRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrintRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PrintRequests.
   */
  distinct?: Prisma.PrintRequestScalarFieldEnum | Prisma.PrintRequestScalarFieldEnum[]
}

/**
 * PrintRequest findFirstOrThrow
 */
export type PrintRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestInclude<ExtArgs> | null
  /**
   * Filter, which PrintRequest to fetch.
   */
  where?: Prisma.PrintRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrintRequests to fetch.
   */
  orderBy?: Prisma.PrintRequestOrderByWithRelationInput | Prisma.PrintRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PrintRequests.
   */
  cursor?: Prisma.PrintRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrintRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrintRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PrintRequests.
   */
  distinct?: Prisma.PrintRequestScalarFieldEnum | Prisma.PrintRequestScalarFieldEnum[]
}

/**
 * PrintRequest findMany
 */
export type PrintRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestInclude<ExtArgs> | null
  /**
   * Filter, which PrintRequests to fetch.
   */
  where?: Prisma.PrintRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrintRequests to fetch.
   */
  orderBy?: Prisma.PrintRequestOrderByWithRelationInput | Prisma.PrintRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PrintRequests.
   */
  cursor?: Prisma.PrintRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrintRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrintRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PrintRequests.
   */
  distinct?: Prisma.PrintRequestScalarFieldEnum | Prisma.PrintRequestScalarFieldEnum[]
}

/**
 * PrintRequest create
 */
export type PrintRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestInclude<ExtArgs> | null
  /**
   * The data needed to create a PrintRequest.
   */
  data: Prisma.XOR<Prisma.PrintRequestCreateInput, Prisma.PrintRequestUncheckedCreateInput>
}

/**
 * PrintRequest createMany
 */
export type PrintRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PrintRequests.
   */
  data: Prisma.PrintRequestCreateManyInput | Prisma.PrintRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PrintRequest createManyAndReturn
 */
export type PrintRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * The data used to create many PrintRequests.
   */
  data: Prisma.PrintRequestCreateManyInput | Prisma.PrintRequestCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PrintRequest update
 */
export type PrintRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestInclude<ExtArgs> | null
  /**
   * The data needed to update a PrintRequest.
   */
  data: Prisma.XOR<Prisma.PrintRequestUpdateInput, Prisma.PrintRequestUncheckedUpdateInput>
  /**
   * Choose, which PrintRequest to update.
   */
  where: Prisma.PrintRequestWhereUniqueInput
}

/**
 * PrintRequest updateMany
 */
export type PrintRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PrintRequests.
   */
  data: Prisma.XOR<Prisma.PrintRequestUpdateManyMutationInput, Prisma.PrintRequestUncheckedUpdateManyInput>
  /**
   * Filter which PrintRequests to update
   */
  where?: Prisma.PrintRequestWhereInput
  /**
   * Limit how many PrintRequests to update.
   */
  limit?: number
}

/**
 * PrintRequest updateManyAndReturn
 */
export type PrintRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * The data used to update PrintRequests.
   */
  data: Prisma.XOR<Prisma.PrintRequestUpdateManyMutationInput, Prisma.PrintRequestUncheckedUpdateManyInput>
  /**
   * Filter which PrintRequests to update
   */
  where?: Prisma.PrintRequestWhereInput
  /**
   * Limit how many PrintRequests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PrintRequest upsert
 */
export type PrintRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestInclude<ExtArgs> | null
  /**
   * The filter to search for the PrintRequest to update in case it exists.
   */
  where: Prisma.PrintRequestWhereUniqueInput
  /**
   * In case the PrintRequest found by the `where` argument doesn't exist, create a new PrintRequest with this data.
   */
  create: Prisma.XOR<Prisma.PrintRequestCreateInput, Prisma.PrintRequestUncheckedCreateInput>
  /**
   * In case the PrintRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PrintRequestUpdateInput, Prisma.PrintRequestUncheckedUpdateInput>
}

/**
 * PrintRequest delete
 */
export type PrintRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestInclude<ExtArgs> | null
  /**
   * Filter which PrintRequest to delete.
   */
  where: Prisma.PrintRequestWhereUniqueInput
}

/**
 * PrintRequest deleteMany
 */
export type PrintRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PrintRequests to delete
   */
  where?: Prisma.PrintRequestWhereInput
  /**
   * Limit how many PrintRequests to delete.
   */
  limit?: number
}

/**
 * PrintRequest without action
 */
export type PrintRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrintRequest
   */
  select?: Prisma.PrintRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrintRequest
   */
  omit?: Prisma.PrintRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrintRequestInclude<ExtArgs> | null
}
