
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SpaceOperatingHours` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SpaceOperatingHours
 * 
 */
export type SpaceOperatingHoursModel = runtime.Types.Result.DefaultSelection<Prisma.$SpaceOperatingHoursPayload>

export type AggregateSpaceOperatingHours = {
  _count: SpaceOperatingHoursCountAggregateOutputType | null
  _min: SpaceOperatingHoursMinAggregateOutputType | null
  _max: SpaceOperatingHoursMaxAggregateOutputType | null
}

export type SpaceOperatingHoursMinAggregateOutputType = {
  spaceId: string | null
}

export type SpaceOperatingHoursMaxAggregateOutputType = {
  spaceId: string | null
}

export type SpaceOperatingHoursCountAggregateOutputType = {
  spaceId: number
  policies: number
  overrides: number
  _all: number
}


export type SpaceOperatingHoursMinAggregateInputType = {
  spaceId?: true
}

export type SpaceOperatingHoursMaxAggregateInputType = {
  spaceId?: true
}

export type SpaceOperatingHoursCountAggregateInputType = {
  spaceId?: true
  policies?: true
  overrides?: true
  _all?: true
}

export type SpaceOperatingHoursAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SpaceOperatingHours to aggregate.
   */
  where?: Prisma.SpaceOperatingHoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpaceOperatingHours to fetch.
   */
  orderBy?: Prisma.SpaceOperatingHoursOrderByWithRelationInput | Prisma.SpaceOperatingHoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SpaceOperatingHoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpaceOperatingHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpaceOperatingHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SpaceOperatingHours
  **/
  _count?: true | SpaceOperatingHoursCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SpaceOperatingHoursMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SpaceOperatingHoursMaxAggregateInputType
}

export type GetSpaceOperatingHoursAggregateType<T extends SpaceOperatingHoursAggregateArgs> = {
      [P in keyof T & keyof AggregateSpaceOperatingHours]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSpaceOperatingHours[P]>
    : Prisma.GetScalarType<T[P], AggregateSpaceOperatingHours[P]>
}




export type SpaceOperatingHoursGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SpaceOperatingHoursWhereInput
  orderBy?: Prisma.SpaceOperatingHoursOrderByWithAggregationInput | Prisma.SpaceOperatingHoursOrderByWithAggregationInput[]
  by: Prisma.SpaceOperatingHoursScalarFieldEnum[] | Prisma.SpaceOperatingHoursScalarFieldEnum
  having?: Prisma.SpaceOperatingHoursScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SpaceOperatingHoursCountAggregateInputType | true
  _min?: SpaceOperatingHoursMinAggregateInputType
  _max?: SpaceOperatingHoursMaxAggregateInputType
}

export type SpaceOperatingHoursGroupByOutputType = {
  spaceId: string
  policies: runtime.JsonValue
  overrides: runtime.JsonValue
  _count: SpaceOperatingHoursCountAggregateOutputType | null
  _min: SpaceOperatingHoursMinAggregateOutputType | null
  _max: SpaceOperatingHoursMaxAggregateOutputType | null
}

type GetSpaceOperatingHoursGroupByPayload<T extends SpaceOperatingHoursGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SpaceOperatingHoursGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SpaceOperatingHoursGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SpaceOperatingHoursGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SpaceOperatingHoursGroupByOutputType[P]>
      }
    >
  >



export type SpaceOperatingHoursWhereInput = {
  AND?: Prisma.SpaceOperatingHoursWhereInput | Prisma.SpaceOperatingHoursWhereInput[]
  OR?: Prisma.SpaceOperatingHoursWhereInput[]
  NOT?: Prisma.SpaceOperatingHoursWhereInput | Prisma.SpaceOperatingHoursWhereInput[]
  spaceId?: Prisma.StringFilter<"SpaceOperatingHours"> | string
  policies?: Prisma.JsonFilter<"SpaceOperatingHours">
  overrides?: Prisma.JsonFilter<"SpaceOperatingHours">
}

export type SpaceOperatingHoursOrderByWithRelationInput = {
  spaceId?: Prisma.SortOrder
  policies?: Prisma.SortOrder
  overrides?: Prisma.SortOrder
}

export type SpaceOperatingHoursWhereUniqueInput = Prisma.AtLeast<{
  spaceId?: string
  AND?: Prisma.SpaceOperatingHoursWhereInput | Prisma.SpaceOperatingHoursWhereInput[]
  OR?: Prisma.SpaceOperatingHoursWhereInput[]
  NOT?: Prisma.SpaceOperatingHoursWhereInput | Prisma.SpaceOperatingHoursWhereInput[]
  policies?: Prisma.JsonFilter<"SpaceOperatingHours">
  overrides?: Prisma.JsonFilter<"SpaceOperatingHours">
}, "spaceId">

export type SpaceOperatingHoursOrderByWithAggregationInput = {
  spaceId?: Prisma.SortOrder
  policies?: Prisma.SortOrder
  overrides?: Prisma.SortOrder
  _count?: Prisma.SpaceOperatingHoursCountOrderByAggregateInput
  _max?: Prisma.SpaceOperatingHoursMaxOrderByAggregateInput
  _min?: Prisma.SpaceOperatingHoursMinOrderByAggregateInput
}

export type SpaceOperatingHoursScalarWhereWithAggregatesInput = {
  AND?: Prisma.SpaceOperatingHoursScalarWhereWithAggregatesInput | Prisma.SpaceOperatingHoursScalarWhereWithAggregatesInput[]
  OR?: Prisma.SpaceOperatingHoursScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SpaceOperatingHoursScalarWhereWithAggregatesInput | Prisma.SpaceOperatingHoursScalarWhereWithAggregatesInput[]
  spaceId?: Prisma.StringWithAggregatesFilter<"SpaceOperatingHours"> | string
  policies?: Prisma.JsonWithAggregatesFilter<"SpaceOperatingHours">
  overrides?: Prisma.JsonWithAggregatesFilter<"SpaceOperatingHours">
}

export type SpaceOperatingHoursCreateInput = {
  spaceId: string
  policies: Prisma.JsonNullValueInput | runtime.InputJsonValue
  overrides: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type SpaceOperatingHoursUncheckedCreateInput = {
  spaceId: string
  policies: Prisma.JsonNullValueInput | runtime.InputJsonValue
  overrides: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type SpaceOperatingHoursUpdateInput = {
  spaceId?: Prisma.StringFieldUpdateOperationsInput | string
  policies?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type SpaceOperatingHoursUncheckedUpdateInput = {
  spaceId?: Prisma.StringFieldUpdateOperationsInput | string
  policies?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type SpaceOperatingHoursCreateManyInput = {
  spaceId: string
  policies: Prisma.JsonNullValueInput | runtime.InputJsonValue
  overrides: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type SpaceOperatingHoursUpdateManyMutationInput = {
  spaceId?: Prisma.StringFieldUpdateOperationsInput | string
  policies?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type SpaceOperatingHoursUncheckedUpdateManyInput = {
  spaceId?: Prisma.StringFieldUpdateOperationsInput | string
  policies?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type SpaceOperatingHoursCountOrderByAggregateInput = {
  spaceId?: Prisma.SortOrder
  policies?: Prisma.SortOrder
  overrides?: Prisma.SortOrder
}

export type SpaceOperatingHoursMaxOrderByAggregateInput = {
  spaceId?: Prisma.SortOrder
}

export type SpaceOperatingHoursMinOrderByAggregateInput = {
  spaceId?: Prisma.SortOrder
}



export type SpaceOperatingHoursSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  spaceId?: boolean
  policies?: boolean
  overrides?: boolean
}, ExtArgs["result"]["spaceOperatingHours"]>

export type SpaceOperatingHoursSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  spaceId?: boolean
  policies?: boolean
  overrides?: boolean
}, ExtArgs["result"]["spaceOperatingHours"]>

export type SpaceOperatingHoursSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  spaceId?: boolean
  policies?: boolean
  overrides?: boolean
}, ExtArgs["result"]["spaceOperatingHours"]>

export type SpaceOperatingHoursSelectScalar = {
  spaceId?: boolean
  policies?: boolean
  overrides?: boolean
}

export type SpaceOperatingHoursOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"spaceId" | "policies" | "overrides", ExtArgs["result"]["spaceOperatingHours"]>

export type $SpaceOperatingHoursPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SpaceOperatingHours"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    spaceId: string
    policies: runtime.JsonValue
    overrides: runtime.JsonValue
  }, ExtArgs["result"]["spaceOperatingHours"]>
  composites: {}
}

export type SpaceOperatingHoursGetPayload<S extends boolean | null | undefined | SpaceOperatingHoursDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload, S>

export type SpaceOperatingHoursCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SpaceOperatingHoursFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SpaceOperatingHoursCountAggregateInputType | true
  }

export interface SpaceOperatingHoursDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SpaceOperatingHours'], meta: { name: 'SpaceOperatingHours' } }
  /**
   * Find zero or one SpaceOperatingHours that matches the filter.
   * @param {SpaceOperatingHoursFindUniqueArgs} args - Arguments to find a SpaceOperatingHours
   * @example
   * // Get one SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SpaceOperatingHoursFindUniqueArgs>(args: Prisma.SelectSubset<T, SpaceOperatingHoursFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SpaceOperatingHoursClient<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SpaceOperatingHours that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SpaceOperatingHoursFindUniqueOrThrowArgs} args - Arguments to find a SpaceOperatingHours
   * @example
   * // Get one SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SpaceOperatingHoursFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SpaceOperatingHoursFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SpaceOperatingHoursClient<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SpaceOperatingHours that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpaceOperatingHoursFindFirstArgs} args - Arguments to find a SpaceOperatingHours
   * @example
   * // Get one SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SpaceOperatingHoursFindFirstArgs>(args?: Prisma.SelectSubset<T, SpaceOperatingHoursFindFirstArgs<ExtArgs>>): Prisma.Prisma__SpaceOperatingHoursClient<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SpaceOperatingHours that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpaceOperatingHoursFindFirstOrThrowArgs} args - Arguments to find a SpaceOperatingHours
   * @example
   * // Get one SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SpaceOperatingHoursFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SpaceOperatingHoursFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SpaceOperatingHoursClient<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SpaceOperatingHours that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpaceOperatingHoursFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.findMany()
   * 
   * // Get first 10 SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.findMany({ take: 10 })
   * 
   * // Only select the `spaceId`
   * const spaceOperatingHoursWithSpaceIdOnly = await prisma.spaceOperatingHours.findMany({ select: { spaceId: true } })
   * 
   */
  findMany<T extends SpaceOperatingHoursFindManyArgs>(args?: Prisma.SelectSubset<T, SpaceOperatingHoursFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SpaceOperatingHours.
   * @param {SpaceOperatingHoursCreateArgs} args - Arguments to create a SpaceOperatingHours.
   * @example
   * // Create one SpaceOperatingHours
   * const SpaceOperatingHours = await prisma.spaceOperatingHours.create({
   *   data: {
   *     // ... data to create a SpaceOperatingHours
   *   }
   * })
   * 
   */
  create<T extends SpaceOperatingHoursCreateArgs>(args: Prisma.SelectSubset<T, SpaceOperatingHoursCreateArgs<ExtArgs>>): Prisma.Prisma__SpaceOperatingHoursClient<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SpaceOperatingHours.
   * @param {SpaceOperatingHoursCreateManyArgs} args - Arguments to create many SpaceOperatingHours.
   * @example
   * // Create many SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SpaceOperatingHoursCreateManyArgs>(args?: Prisma.SelectSubset<T, SpaceOperatingHoursCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SpaceOperatingHours and returns the data saved in the database.
   * @param {SpaceOperatingHoursCreateManyAndReturnArgs} args - Arguments to create many SpaceOperatingHours.
   * @example
   * // Create many SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SpaceOperatingHours and only return the `spaceId`
   * const spaceOperatingHoursWithSpaceIdOnly = await prisma.spaceOperatingHours.createManyAndReturn({
   *   select: { spaceId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SpaceOperatingHoursCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SpaceOperatingHoursCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SpaceOperatingHours.
   * @param {SpaceOperatingHoursDeleteArgs} args - Arguments to delete one SpaceOperatingHours.
   * @example
   * // Delete one SpaceOperatingHours
   * const SpaceOperatingHours = await prisma.spaceOperatingHours.delete({
   *   where: {
   *     // ... filter to delete one SpaceOperatingHours
   *   }
   * })
   * 
   */
  delete<T extends SpaceOperatingHoursDeleteArgs>(args: Prisma.SelectSubset<T, SpaceOperatingHoursDeleteArgs<ExtArgs>>): Prisma.Prisma__SpaceOperatingHoursClient<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SpaceOperatingHours.
   * @param {SpaceOperatingHoursUpdateArgs} args - Arguments to update one SpaceOperatingHours.
   * @example
   * // Update one SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SpaceOperatingHoursUpdateArgs>(args: Prisma.SelectSubset<T, SpaceOperatingHoursUpdateArgs<ExtArgs>>): Prisma.Prisma__SpaceOperatingHoursClient<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SpaceOperatingHours.
   * @param {SpaceOperatingHoursDeleteManyArgs} args - Arguments to filter SpaceOperatingHours to delete.
   * @example
   * // Delete a few SpaceOperatingHours
   * const { count } = await prisma.spaceOperatingHours.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SpaceOperatingHoursDeleteManyArgs>(args?: Prisma.SelectSubset<T, SpaceOperatingHoursDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SpaceOperatingHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpaceOperatingHoursUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SpaceOperatingHoursUpdateManyArgs>(args: Prisma.SelectSubset<T, SpaceOperatingHoursUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SpaceOperatingHours and returns the data updated in the database.
   * @param {SpaceOperatingHoursUpdateManyAndReturnArgs} args - Arguments to update many SpaceOperatingHours.
   * @example
   * // Update many SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SpaceOperatingHours and only return the `spaceId`
   * const spaceOperatingHoursWithSpaceIdOnly = await prisma.spaceOperatingHours.updateManyAndReturn({
   *   select: { spaceId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SpaceOperatingHoursUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SpaceOperatingHoursUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SpaceOperatingHours.
   * @param {SpaceOperatingHoursUpsertArgs} args - Arguments to update or create a SpaceOperatingHours.
   * @example
   * // Update or create a SpaceOperatingHours
   * const spaceOperatingHours = await prisma.spaceOperatingHours.upsert({
   *   create: {
   *     // ... data to create a SpaceOperatingHours
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SpaceOperatingHours we want to update
   *   }
   * })
   */
  upsert<T extends SpaceOperatingHoursUpsertArgs>(args: Prisma.SelectSubset<T, SpaceOperatingHoursUpsertArgs<ExtArgs>>): Prisma.Prisma__SpaceOperatingHoursClient<runtime.Types.Result.GetResult<Prisma.$SpaceOperatingHoursPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SpaceOperatingHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpaceOperatingHoursCountArgs} args - Arguments to filter SpaceOperatingHours to count.
   * @example
   * // Count the number of SpaceOperatingHours
   * const count = await prisma.spaceOperatingHours.count({
   *   where: {
   *     // ... the filter for the SpaceOperatingHours we want to count
   *   }
   * })
  **/
  count<T extends SpaceOperatingHoursCountArgs>(
    args?: Prisma.Subset<T, SpaceOperatingHoursCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SpaceOperatingHoursCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SpaceOperatingHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpaceOperatingHoursAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SpaceOperatingHoursAggregateArgs>(args: Prisma.Subset<T, SpaceOperatingHoursAggregateArgs>): Prisma.PrismaPromise<GetSpaceOperatingHoursAggregateType<T>>

  /**
   * Group by SpaceOperatingHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpaceOperatingHoursGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SpaceOperatingHoursGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SpaceOperatingHoursGroupByArgs['orderBy'] }
      : { orderBy?: SpaceOperatingHoursGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SpaceOperatingHoursGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSpaceOperatingHoursGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SpaceOperatingHours model
 */
readonly fields: SpaceOperatingHoursFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SpaceOperatingHours.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SpaceOperatingHoursClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SpaceOperatingHours model
 */
export interface SpaceOperatingHoursFieldRefs {
  readonly spaceId: Prisma.FieldRef<"SpaceOperatingHours", 'String'>
  readonly policies: Prisma.FieldRef<"SpaceOperatingHours", 'Json'>
  readonly overrides: Prisma.FieldRef<"SpaceOperatingHours", 'Json'>
}
    

// Custom InputTypes
/**
 * SpaceOperatingHours findUnique
 */
export type SpaceOperatingHoursFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * Filter, which SpaceOperatingHours to fetch.
   */
  where: Prisma.SpaceOperatingHoursWhereUniqueInput
}

/**
 * SpaceOperatingHours findUniqueOrThrow
 */
export type SpaceOperatingHoursFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * Filter, which SpaceOperatingHours to fetch.
   */
  where: Prisma.SpaceOperatingHoursWhereUniqueInput
}

/**
 * SpaceOperatingHours findFirst
 */
export type SpaceOperatingHoursFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * Filter, which SpaceOperatingHours to fetch.
   */
  where?: Prisma.SpaceOperatingHoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpaceOperatingHours to fetch.
   */
  orderBy?: Prisma.SpaceOperatingHoursOrderByWithRelationInput | Prisma.SpaceOperatingHoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SpaceOperatingHours.
   */
  cursor?: Prisma.SpaceOperatingHoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpaceOperatingHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpaceOperatingHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SpaceOperatingHours.
   */
  distinct?: Prisma.SpaceOperatingHoursScalarFieldEnum | Prisma.SpaceOperatingHoursScalarFieldEnum[]
}

/**
 * SpaceOperatingHours findFirstOrThrow
 */
export type SpaceOperatingHoursFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * Filter, which SpaceOperatingHours to fetch.
   */
  where?: Prisma.SpaceOperatingHoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpaceOperatingHours to fetch.
   */
  orderBy?: Prisma.SpaceOperatingHoursOrderByWithRelationInput | Prisma.SpaceOperatingHoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SpaceOperatingHours.
   */
  cursor?: Prisma.SpaceOperatingHoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpaceOperatingHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpaceOperatingHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SpaceOperatingHours.
   */
  distinct?: Prisma.SpaceOperatingHoursScalarFieldEnum | Prisma.SpaceOperatingHoursScalarFieldEnum[]
}

/**
 * SpaceOperatingHours findMany
 */
export type SpaceOperatingHoursFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * Filter, which SpaceOperatingHours to fetch.
   */
  where?: Prisma.SpaceOperatingHoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpaceOperatingHours to fetch.
   */
  orderBy?: Prisma.SpaceOperatingHoursOrderByWithRelationInput | Prisma.SpaceOperatingHoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SpaceOperatingHours.
   */
  cursor?: Prisma.SpaceOperatingHoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpaceOperatingHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpaceOperatingHours.
   */
  skip?: number
  distinct?: Prisma.SpaceOperatingHoursScalarFieldEnum | Prisma.SpaceOperatingHoursScalarFieldEnum[]
}

/**
 * SpaceOperatingHours create
 */
export type SpaceOperatingHoursCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * The data needed to create a SpaceOperatingHours.
   */
  data: Prisma.XOR<Prisma.SpaceOperatingHoursCreateInput, Prisma.SpaceOperatingHoursUncheckedCreateInput>
}

/**
 * SpaceOperatingHours createMany
 */
export type SpaceOperatingHoursCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SpaceOperatingHours.
   */
  data: Prisma.SpaceOperatingHoursCreateManyInput | Prisma.SpaceOperatingHoursCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SpaceOperatingHours createManyAndReturn
 */
export type SpaceOperatingHoursCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * The data used to create many SpaceOperatingHours.
   */
  data: Prisma.SpaceOperatingHoursCreateManyInput | Prisma.SpaceOperatingHoursCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SpaceOperatingHours update
 */
export type SpaceOperatingHoursUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * The data needed to update a SpaceOperatingHours.
   */
  data: Prisma.XOR<Prisma.SpaceOperatingHoursUpdateInput, Prisma.SpaceOperatingHoursUncheckedUpdateInput>
  /**
   * Choose, which SpaceOperatingHours to update.
   */
  where: Prisma.SpaceOperatingHoursWhereUniqueInput
}

/**
 * SpaceOperatingHours updateMany
 */
export type SpaceOperatingHoursUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SpaceOperatingHours.
   */
  data: Prisma.XOR<Prisma.SpaceOperatingHoursUpdateManyMutationInput, Prisma.SpaceOperatingHoursUncheckedUpdateManyInput>
  /**
   * Filter which SpaceOperatingHours to update
   */
  where?: Prisma.SpaceOperatingHoursWhereInput
  /**
   * Limit how many SpaceOperatingHours to update.
   */
  limit?: number
}

/**
 * SpaceOperatingHours updateManyAndReturn
 */
export type SpaceOperatingHoursUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * The data used to update SpaceOperatingHours.
   */
  data: Prisma.XOR<Prisma.SpaceOperatingHoursUpdateManyMutationInput, Prisma.SpaceOperatingHoursUncheckedUpdateManyInput>
  /**
   * Filter which SpaceOperatingHours to update
   */
  where?: Prisma.SpaceOperatingHoursWhereInput
  /**
   * Limit how many SpaceOperatingHours to update.
   */
  limit?: number
}

/**
 * SpaceOperatingHours upsert
 */
export type SpaceOperatingHoursUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * The filter to search for the SpaceOperatingHours to update in case it exists.
   */
  where: Prisma.SpaceOperatingHoursWhereUniqueInput
  /**
   * In case the SpaceOperatingHours found by the `where` argument doesn't exist, create a new SpaceOperatingHours with this data.
   */
  create: Prisma.XOR<Prisma.SpaceOperatingHoursCreateInput, Prisma.SpaceOperatingHoursUncheckedCreateInput>
  /**
   * In case the SpaceOperatingHours was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SpaceOperatingHoursUpdateInput, Prisma.SpaceOperatingHoursUncheckedUpdateInput>
}

/**
 * SpaceOperatingHours delete
 */
export type SpaceOperatingHoursDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
  /**
   * Filter which SpaceOperatingHours to delete.
   */
  where: Prisma.SpaceOperatingHoursWhereUniqueInput
}

/**
 * SpaceOperatingHours deleteMany
 */
export type SpaceOperatingHoursDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SpaceOperatingHours to delete
   */
  where?: Prisma.SpaceOperatingHoursWhereInput
  /**
   * Limit how many SpaceOperatingHours to delete.
   */
  limit?: number
}

/**
 * SpaceOperatingHours without action
 */
export type SpaceOperatingHoursDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpaceOperatingHours
   */
  select?: Prisma.SpaceOperatingHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpaceOperatingHours
   */
  omit?: Prisma.SpaceOperatingHoursOmit<ExtArgs> | null
}
