name: Deploy Prod API

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy for API
        run: |
          curl --request GET \
            --url "https://coolify-vps.inova.ma.gov.br/api/v1/deploy?uuid=xrdq06jsqb2h8skkdrznqopg&force=false" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_TOKEN }}"
