name: Deploy Dev Mobile

on:
  push:
    branches:
      - dev
    paths:
      - 'apps/mobile/**'
      - 'apps/api/**'

jobs:
  deploy-mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy for Mobile
        run: |
          curl --request GET \
            --url "https://coolify-vps.inova.ma.gov.br/api/v1/deploy?uuid=slrtw03j8znfy0t9zt4ecynl&force=false" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_TOKEN }}"
